### ISSUE TITLE
ERROR    src.imageCreate -> Error while create image: Redirect failed

### ISSUE THREAD

**Issue by BuGz91** [FuseFairy/DiscordBot-EdgeGPT#100]
I give this error in terminal, when i want to a generate a image:

Traceback (most recent call last):
  File "/home/pi/BING/src/imageCreate.py", line 20, in create_image
    images = await image_generator.get_images(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/BingImageCreator.py", line 312, in get_images
    raise Exception("Redirect failed")
Exception: Redirect failed

**Comment by FuseFairy** [comment]
Update BingImageCreator or try update cookies again
```
pip install BingImageCreator --upgrade
```

**Comment by FuseFairy** [comment]
Emmm, l'm not sure what going run, try vpn or use another account cookies. I will keep looking for a solution.

**Comment by FuseFairy** [comment]
Update new version, the problem was solved
