### ISSUE TITLE
Implement incoming image recognition and human language drawing

### ISSUE THREAD

**Issue by canxin121** [FuseFairy/DiscordBot-EdgeGPT#101]
This Lib may help you Implement them.

And it also allow user to use bing even if bing is at access_token mode.

[ Async-Bing-Client ](https://github.com/canxin121/Async-Bing-Client)
<img width="621" alt="image" src="https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/69547456/eeba93f7-c121-4d6c-8c34-a316cbf1e57a">

**Comment by FuseFairy** [comment]
That's very helpful, I just needed it!
