### ISSUE TITLE
'conversationSignature' error

### ISSUE THREAD

**Issue by de-joit** [FuseFairy/DiscordBot-EdgeGPT#102]
Exception has occurred: KeyError
'conversationSignature'
  File "C:\Users\VovaLT\Downloads\DiscordBot-EdgeGPT-main\cogs\event.py", line 27, in <module>
    chatbot = Chatbot(cookies=cookies)
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\VovaLT\Downloads\DiscordBot-EdgeGPT-main\bot.py", line 8, in <module>
    from cogs.event import set_chatbot
KeyError: 'conversationSignature'

Getting some error. Updated cookies few times, used vpn - nothing helped.

**Comment by FuseFairy** [comment]
I'm will update repo to use another api

**Comment by de-joit** [comment]
Thank you very much! Take as much time as you need :)

**Comment by herowarriors0** [comment]
I have the same issue.

**Comment by ChaayaOne** [comment]
Hey! As of today, im still encountering the error, is it just for me or you have not fixed it yet? Thanks

**Comment by sinuso** [comment]
> Hey, you closed this issue but its still hapenning to me: Traceback (most recent call last): File "C:\Users\peter\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\bot.py", line 8, in from cogs.event import set_chatbot File "C:\Users\peter\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\cogs\event.py", line 27, in chatbot = Chatbot(cookies=cookies) File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\site-packages\EdgeGPT\EdgeGPT.py", line 28, in **init** self.chat_hub: ChatHub = ChatHub( File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\site-packages\EdgeGPT\chathub.py", line 41, in **init** conversation_signature=conversation.struct["conversationSignature"], KeyError: 'conversationSignature'

I have the same error.

**Comment by FuseFairy** [comment]
Will update next month, I’ve been - quite busy lately

**Comment by herowarriors0** [comment]
Thanks, that would be soo good

**Comment by FuseFairy** [comment]
update is complete

**Comment by de-joit** [comment]
yay, i think it's working now, thank you very much!
