### ISSUE TITLE
Error when starting the bot

### ISSUE THREAD

**Issue by herowarriors0** [FuseFairy/DiscordBot-EdgeGPT#103]
The bot stopped working. This is the error:

Exception has occurred: KeyError
'conversationSignature'
File "C:\Users\hero\Fontos\DiscordBot-EdgeGPT-main\cogs\event.py", line 27, in
chatbot = Chatbot(cookies=cookies)
^^^^^^^^^^^^^^^^
File "C:\Users\hero\Fontos\DiscordBot-EdgeGPT-main\bot.py", line 8, in
from cogs.event import set_chatbot
KeyError: 'conversationSignature'

What should I do?

**Comment by FuseFairy** [comment]
https://github.com/FuseFairy/DiscordBot-EdgeGPT/issues/102

**Comment by herowarriors0** [comment]
Oh I didn't see that one.
