### ISSUE TITLE
Use the cookes that were uploaded by the author.

### ISSUE THREAD

**Issue by herowarriors0** [FuseFairy/DiscordBot-EdgeGPT#104]
Hi! How can I make that the default option, that when I use the slash commands, it will automaticly use the cookies that were uploaded by the author? I don't want to make everyone use the /bing_setting set command.

**Comment by FuseFairy** [comment]
the easy way is change cog/edgegpt.py like this

```
import discord
import json
from typing import Optional
from discord import app_commands
from core.classes import Cog_Extension
from src import log
from src.user_chatbot import set_chatbot, get_users_chatbot, del_users_chatbot

logger = log.setup_logger(__name__)

class EdgeGPT(Cog_Extension):
    # Set or delete Bing chatbot.
    # @app_commands.command(name="bing_setting", description="Set or delete bing chatbot.")
    # @app_commands.choices(choice=[app_commands.Choice(name="set", value="set"), app_commands.Choice(name="delete", value="delete")])
    # async def cookies_setting(self, interaction: discord.Interaction, choice: app_commands.Choice[str], cookies_file: Optional[discord.Attachment]=None):
    #     await interaction.response.defer(ephemeral=True, thinking=True)
    #     user_id = interaction.user.id
    #     if choice.value == "set":
    #         if cookies_file is not None:
    #             cookies = json.loads(await cookies_file.read())
    #             await set_chatbot(user_id, cookies)
    #             await interaction.followup.send("> **INFO: Chatbot set successful!**")
    #             logger.info(f"{interaction.user} set Bing Chatbot successful")
    #         else:
    #             await set_chatbot(user_id)
    #             await interaction.followup.send("> **INFO: Chatbot set successful! (using bot owner cookies)**")
    #             logger.info(f"{interaction.user} set Bing chatbot successful. (using bot owner cookies)")
    #     else:
    #         users_chatbot = get_users_chatbot()
    #         if user_id in users_chatbot:
    #             del_users_chatbot(user_id)
    #             await interaction.followup.send("> **INFO: Delete your Bing chatbot completely.**")
    #             logger.info(f"Delete {interaction.user} Cookies.")
    #         else:
    #             await interaction.followup.send("> **ERROR: You don't have any Bing chatbot yet.**")

    # Chat with Bing.
    @app_commands.command(name="bing", description="Have a chat with Bing")
    async def bing(self, interaction: discord.Interaction, *, message: str):
        users_chatbot = get_users_chatbot()
        username = interaction.user
        usermessage = message
        channel = interaction.channel
        user_id = interaction.user.id
        if user_id not in users_chatbot:
            await set_chatbot(user_id)
            # await interaction.response.defer(ephemeral=True, thinking=True)
            # await interaction.followup.send("> **ERROE: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
        logger.info(f"{username}: {usermessage} ({channel}) [Style: {users_chatbot[user_id].get_conversation_style()}]")
        await users_chatbot[user_id].send_message(interaction, usermessage)

    # Switch conversation style.
    @app_commands.command(name="switch_style", description="Switch conversation style")
    @app_commands.choices(style=[app_commands.Choice(name="Creative", value="creative"), app_commands.Choice(name="Balanced", value="balanced"), app_commands.Choice(name="Precise", value="precise")])
    async def switch_style(self, interaction: discord.Interaction, style: app_commands.Choice[str]):
        await interaction.response.defer(ephemeral=True, thinking=True)
        users_chatbot = get_users_chatbot()
        user_id = interaction.user.id
        if user_id not in users_chatbot:
            await interaction.followup.send("> **ERROR: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
        users_chatbot[user_id].set_conversation_style(style.value)
        await interaction.followup.send(f"> **INFO: successfull switch conversation style to {style.value}.**")
        
    # Create images.
    @app_commands.command(name="create_image", description="generate image by Bing image creator")
    async def create_image(self, interaction: discord.Interaction, *, prompt: str):
        users_chatbot = get_users_chatbot()
        user_id = interaction.user.id
        if user_id not in users_chatbot:
            await interaction.response.defer(ephemeral=True, thinking=True)
            await interaction.followup.send("> **ERROR: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
        await interaction.response.defer(ephemeral=False, thinking=True)
        await users_chatbot[user_id].create_image(interaction, prompt)
    
    # Reset conversation
    @app_commands.command(name="reset_conversation", description="Reset bing chatbot conversation.")
    async def reset_conversation(self, interaction: discord.Interaction):
        users_chatbot = get_users_chatbot()
        user_id = interaction.user.id
        if user_id not in users_chatbot:
            await interaction.response.defer(ephemeral=True, thinking=True)
            await interaction.followup.send("> **ERROR: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
        await interaction.response.defer(ephemeral=True, thinking=True)
        await users_chatbot[user_id].reset_conversation()
        await interaction.followup.send(f"> **Info: Reset finish.**")
        

async def setup(bot):
    await bot.add_cog(EdgeGPT(bot))
```

**Comment by de-joit** [comment]
> if you don't need `/bing_setting`, the easiest way is to change cogs/edgegpt.py like this
Thank you, also needed that! However, I lost the ability to use commands. I can talk with a bot (by pinging it), press buttons (suggested answers or something), and even if I'm pressing buttons from a different account. But can't use commands (resetting conversation, generate images, changing style, etc), it asking for
> ERROR: Please use   `/chatbot_setting`   to set yourself Bing chatbot first.

**Comment by de-joit** [comment]
> if you don't need `/bing_setting`, the easiest way is to change cogs/edgegpt.py like this

Thank you, also needed that! However, I lost the ability to use commands. I can talk with a bot (by pinging it), press buttons (suggested answers or something), and even if I'm pressing buttons from a different account. But can't use commands (resetting conversation, generate images, changing style, etc), it asking for:

> ERROR: Please use   `/chatbot_setting`   to set yourself Bing chatbot first.

Tho, when i'm using /bing and asking something it answers and i can use commands, but loosing the ability to press buttons on different account, says:

>You don't have permission to press this button.

is there a way to make it useable by everyone (for example by my friends on same server) with one cookie (basically cookies.json)? and everyone can talk in the same conversation, as well as press suggested answers?

**Comment by FuseFairy** [comment]
If you want use same conversation, just mention bot, slash command is personal conversation

**Comment by FuseFairy** [comment]
If you want use same conversation, just mention bot, slash command is personal conversation

**Comment by FuseFairy** [comment]
> if you don't need `/bing_setting`, the easiest way is to change cogs/edgegpt.py like this
> 
> ```
> import discord
> import json
> from typing import Optional
> from discord import app_commands
> from core.classes import Cog_Extension
> from src import log
> from src.user_chatbot import set_chatbot, get_users_chatbot, del_users_chatbot
> 
> logger = log.setup_logger(__name__)
> 
> class EdgeGPT(Cog_Extension):
>     # Set or delete Bing chatbot.
>     # @app_commands.command(name="bing_setting", description="Set or delete bing chatbot.")
>     # @app_commands.choices(choice=[app_commands.Choice(name="set", value="set"), app_commands.Choice(name="delete", value="delete")])
>     # async def cookies_setting(self, interaction: discord.Interaction, choice: app_commands.Choice[str], cookies_file: Optional[discord.Attachment]=None):
>     #     await interaction.response.defer(ephemeral=True, thinking=True)
>     #     user_id = interaction.user.id
>     #     if choice.value == "set":
>     #         if cookies_file is not None:
>     #             cookies = json.loads(await cookies_file.read())
>     #             await set_chatbot(user_id, cookies)
>     #             await interaction.followup.send("> **INFO: Chatbot set successful!**")
>     #             logger.info(f"{interaction.user} set Bing Chatbot successful")
>     #         else:
>     #             await set_chatbot(user_id)
>     #             await interaction.followup.send("> **INFO: Chatbot set successful! (using bot owner cookies)**")
>     #             logger.info(f"{interaction.user} set Bing chatbot successful. (using bot owner cookies)")
>     #     else:
>     #         users_chatbot = get_users_chatbot()
>     #         if user_id in users_chatbot:
>     #             del_users_chatbot(user_id)
>     #             await interaction.followup.send("> **INFO: Delete your Bing chatbot completely.**")
>     #             logger.info(f"Delete {interaction.user} Cookies.")
>     #         else:
>     #             await interaction.followup.send("> **ERROR: You don't have any Bing chatbot yet.**")
> 
>     # Chat with Bing.
>     @app_commands.command(name="bing", description="Have a chat with Bing")
>     async def bing(self, interaction: discord.Interaction, *, message: str):
>         users_chatbot = get_users_chatbot()
>         username = interaction.user
>         usermessage = message
>         channel = interaction.channel
>         user_id = interaction.user.id
>         if user_id not in users_chatbot:
>             await set_chatbot(user_id)
>             # await interaction.response.defer(ephemeral=True, thinking=True)
>             # await interaction.followup.send("> **ERROE: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
>         logger.info(f"{username}: {usermessage} ({channel}) [Style: {users_chatbot[user_id].get_conversation_style()}]")
>         await users_chatbot[user_id].send_message(interaction, usermessage)
> 
>     # Switch conversation style.
>     @app_commands.command(name="switch_style", description="Switch conversation style")
>     @app_commands.choices(style=[app_commands.Choice(name="Creative", value="creative"), app_commands.Choice(name="Balanced", value="balanced"), app_commands.Choice(name="Precise", value="precise")])
>     async def switch_style(self, interaction: discord.Interaction, style: app_commands.Choice[str]):
>         await interaction.response.defer(ephemeral=True, thinking=True)
>         users_chatbot = get_users_chatbot()
>         user_id = interaction.user.id
>         if user_id not in users_chatbot:
>             await set_chatbot(user_id)
>             #await interaction.followup.send("> **ERROR: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
>         users_chatbot[user_id].set_conversation_style(style.value)
>         await interaction.followup.send(f"> **INFO: successfull switch conversation style to {style.value}.**")
>         
>     # Create images.
>     @app_commands.command(name="create_image", description="generate image by Bing image creator")
>     async def create_image(self, interaction: discord.Interaction, *, prompt: str):
>         users_chatbot = get_users_chatbot()
>         user_id = interaction.user.id
>         if user_id not in users_chatbot:
>             await set_chatbot(user_id)
>             # await interaction.response.defer(ephemeral=True, thinking=True)
>             # await interaction.followup.send("> **ERROR: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
>         await interaction.response.defer(ephemeral=False, thinking=True)
>         await users_chatbot[user_id].create_image(interaction, prompt)
>     
>     # Reset conversation
>     @app_commands.command(name="reset_conversation", description="Reset bing chatbot conversation.")
>     async def reset_conversation(self, interaction: discord.Interaction):
>         users_chatbot = get_users_chatbot()
>         user_id = interaction.user.id
>         if user_id not in users_chatbot:
>             await set_chatbot(user_id)
>             # await interaction.response.defer(ephemeral=True, thinking=True)
>             # await interaction.followup.send("> **ERROR: Please use  ` /chatbot_setting`   to set yourself Bing chatbot first.**")
>         await interaction.response.defer(ephemeral=True, thinking=True)
>         await users_chatbot[user_id].reset_conversation()
>         await interaction.followup.send(f"> **Info: Reset finish.**")
>         
> 
> async def setup(bot):
>     await bot.add_cog(EdgeGPT(bot))
> ```

try again, I'm edited

**Comment by de-joit** [comment]
>  slash command is use for personal conversation

oh right, thank you! used edited code, i think everything is working as it should ❤
