### ISSUE TITLE
Can I change the timeout limit somehow?

### ISSUE THREAD

**Issue by herowarriors0** [FuseFairy/DiscordBot-EdgeGPT#106]
Bing Image Creator has now a limit of how many times it can generate images quickly. After that, it will take much longer to generate an image, and the bot always says "Timeout". Can I change the timeout limit?

**Comment by FuseFairy** [comment]
change at src/image_create.py

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/0ba9bbc1-38e8-4bb4-a800-654ed01f2d67)

**Comment by herowarriors0** [comment]
Sorry for being so dumb, but what do I need to type? Or how do I change that?

**Comment by FuseFairy** [comment]
```
images = await async_gen.get_images(prompt=prompt, timeout=1000)
```

**Comment by herowarriors0** [comment]
Thanks!
