### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by kukucsi** [FuseFairy/DiscordBot-EdgeGPT#107]
Hi! I have some cool ideas for your amazing bot!

Bing has a "surprise me" button, which is really cool! You could make a /surprise command as well.

Also, I would really like to see a "regenerate" button after an image generates.

These are just recommendations, so if you don't have time or you don't want to make these, it's all right :D.

**Comment by FuseFairy** [comment]
Api doesn't support surprise, but I can try to create /regenerate function.
