### ISSUE TITLE
Discloud hosting, problem with image generator and URL.

### ISSUE THREAD

**Issue by de-joit** [FuseFairy/DiscordBot-EdgeGPT#108]
Not really related to the actual code because it's working pretty well locally on my PC. However, for some odd reason, when I'm using a free hosting service called "Discloud," it gives me an error when trying to generate an image:

> Error: 400 Bad Request (error code: 50035): Invalid Form Body
> In embeds.0.image.url: Not a well-formed URL.

I have tried to fix it myself, but nothing has helped. I suspect it is something with their hosting. Is it possible to somehow bypass this issue, or should I contact their support?

**Comment by FuseFairy** [comment]
I think the host don't like image url which Bing Image Creator return.

**Comment by de-joit** [comment]
Yeah, I remember when the bot downloaded pictures to the /pic folder and sent them as files. I tried to adapt the old code to the new API, but I'm not strong enough in Python and didn't figure out how to do it 😅

**Comment by FuseFairy** [comment]
I'm too busy to help you right now, you can choose another server.

**Comment by de-joit** [comment]
alright, gonna experiment then, thanks!
