### ISSUE TITLE
Suggestion (not a bug) 

### ISSUE THREAD

**Issue by estrizal** [FuseFairy/DiscordBot-EdgeGPT#110]
1) Could you make it so that when we reply to its message, it could reply us back with suitable response (without using  "/"commands. just replying to what she might have previously answered)  

2) Also, please make it so that whenever it gets the Sydney token error, it automatically resets conversation and retries with the given query. 

3) Also, mentioning the bot doesn't do anything. (I thought it will give option to change its style)

**Comment by FuseFairy** [comment]
Will give option when you mentioning the bot.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/0c6e23ae-5aba-41b7-9aa9-e513ebfa2bb8)

**Comment by estrizal** [comment]
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/87994109/d115d201-ad7b-4cc0-8cae-12e45e14e99a)
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/87994109/60770c01-c6e7-42bf-9d66-1e5705781208)

IDK why mine isn't working.

**Comment by FuseFairy** [comment]
I guess your `MENTION_CHANNEL_ID` is wrong, please check again.

**Comment by estrizal** [comment]
Ohhh... Thanks man. It works now. 
I placed the server ID there instead of channel id xd. now it works like a charm. 
but idk why. when I use "@bot generate image" it doesn't generate images. /create command works though (no error in terminal though)
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/87994109/518a5fc3-f226-4874-b9bf-868cd6576a2c)

**Comment by FuseFairy** [comment]
The bing website can create images from conversations, but the api I'm using can't, which is a bit of an anomaly at the moment
