### ISSUE TITLE
Automatic reset

### ISSUE THREAD

**Issue by kukucsi** [FuseFairy/DiscordBot-EdgeGPT#112]
Hi! When I use the /bing command, it mostly returns the `UnauthorizedRequest` error. When this happens, I have to do the /reset command. I was just wondering if it would be possible that the bot automaticly resets if this error occures, and after that it sends the request again to Bing (without sending the error in Discord, just the answer, and nobody knows that in the background it did a reset). This would be super helpful, but if this is impossible or you don't have the time for this, than I can understand that.

**Comment by FuseFairy** [comment]
but `UnauthorizedRequest` error must reset your cookies

**Comment by FuseFairy** [comment]
`UnauthorizedRequest` need reset your cookies, you mean /reset can fix it?
https://reedgegpt.readthedocs.io/en/latest/docs/QA.html

**Comment by kukucsi** [comment]
Yes, I mean I have to put in the /reset command every time, to fix this error. My suggestion is, that the bot should automaticly reset, if this error returns (and the person who puts in the command, just gets's the answer without making a reset and running the same command again.)

**Comment by FuseFairy** [comment]
I haven't figured out the proper way to do this yet, so it may take some time.

**Comment by kukucsi** [comment]
It's not urgent at all, it's just a suggestion.

**Comment by j1seki** [comment]
I was going to search for an answer as he says that would be great to not do /reset each time but automatically does itself.

**Comment by FuseFairy** [comment]
After reset, the previous conversation will close, unsure of the need to re-send the message.
