### ISSUE TITLE
Image attachment with /bing

### ISSUE THREAD

**Issue by kukucsi** [FuseFairy/DiscordBot-EdgeGPT#114]
Hi! I saw that you made it so when using @bot, it can understand images as weell. It would be really cool to see an optional image upload button when using /bing and than it would work the same way.

**Comment by FuseFairy** [comment]
/bing can also upload image.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/fd274293-8829-4ae4-80da-6d5afa0709bb)
