### ISSUE TITLE
Unauthorized Request Error

### ISSUE THREAD

**Issue by cauvang32** [FuseFairy/DiscordBot-EdgeGPT#118]
Error: UnauthorizedRequest: Token issued by https://sydney.bing.com/sydney is invalid (IDX10223: Lifetime validation failed. The token is expired. ValidTo (UTC): '12/30/2023 4:47:06 PM', Current time (UTC): '12/31/2023 2:20:21 PM'.)

- I get this error when using mention to my bot. It usually happens for about 12->15 hours after I make a new cookies.json (because the previous cookies are invalid now).
-> How to solve this or how to make the bot automatically regenerate the cookies.json file?

**Comment by FuseFairy** [comment]
Here's the solution.
https://reedgegpt.readthedocs.io/en/latest/docs/QA.html

**Comment by cauvang32** [comment]
Thanks, can you suggest for me some proxy which can avoid this error?

**Comment by FuseFairy** [comment]
The easiest way to do this is to host the bot up to a server in another country.

**Comment by cauvang32** [comment]
thanks you, that help me much:))
