### ISSUE TITLE
Error while running: module src.log not found

### ISSUE THREAD

**Issue by NiceSapien** [FuseFairy/DiscordBot-EdgeGPT#119]
Hey there!
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/71333407/7a57b21c-6f66-4cb0-bdf6-0f96c2aabc83)
I'm no python programmer, so i am unable to fix this error. I've done everything correctly. Please help me!

**Comment by FuseFairy** [comment]
I fixed the bug https://github.com/FuseFairy/DiscordBot-EdgeGPT/commit/a1c1d25621e6082a9d8c4a9a80d86db1eb66442f

**Comment by NiceSapien** [comment]
Thanks for the fix! But i got another error 😔 
![new error](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/71333407/b2778c21-0d0a-4764-b967-3755833126f5)

**Comment by FuseFairy** [comment]
Try to use python 3.9.16

**Comment by NiceSapien** [comment]
> Try to use python 3.9.16

Do you know how to change python version in replit? I couldn't find anything useful that could help with that

**Comment by FuseFairy** [comment]
https://ask.replit.com/t/how-to-downgrade-python-version-in-replit/44108/2

**Comment by NiceSapien** [comment]
anyways it worked, thanks. I tried it on another host.
