### ISSUE TITLE
 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by estrizal** [FuseFairy/DiscordBot-EdgeGPT#120]
The Image Creating feature is not working. it's just saying "none type" object is not iterable. For Every promp. I tried changing the cookies, but didn't work.. 
maybe re_edge_gpt Api dead?
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/87994109/ce87dd66-4875-415b-9502-33f6434d051f)

I kidnapped some of your image gen code for my telebot too. it's giving the same error (as expected)

Out_of_the_topic:-  Check out the "/doubt" command and "arreyy" function of my mizuhara-discord-bot-repo. I implemented the automatically reset thingy...  There. (by try and except). though I removed the user_chatbot completely, as it wasn't needed there.

**Comment by FuseFairy** [comment]
Are you using the latest version? Because it's working fine for me.

**Comment by estrizal** [comment]
Yup. works now.
