### ISSUE TITLE
On mobile, when using the image creation, only the first image is displayed.

### ISSUE THREAD

**Issue by xXG0DLessXx** [FuseFairy/DiscordBot-EdgeGPT#121]
On desktop and web, it shows all generated images. On mobile it only shows the first. If the first image couldn’t be generated, it shows empty even though there are other images generated… Maybe an issue due to the new mobile discord design? Not sure.
<img width="375" alt="image" src="https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/40996215/c86fc908-9cf6-4499-a597-44ed03bc3595">

**Comment by FuseFairy** [comment]
Is the mobile an ios system?

**Comment by xXG0DLessXx** [comment]
> Is the mobile an ios system?

Yes I am on iOS.

**Comment by FuseFairy** [comment]
In fact, the ios discord does have some problems, I will add the link button after or through other methods.

**Comment by FuseFairy** [comment]
Upgrading to ver1.1.0 will solve the problem.

**Comment by xXG0DLessXx** [comment]
> Upgrading to ver1.1.0 will solve the problem.

I just upgraded, and now the docker container won't start... Here the error logs:
Traceback (most recent call last):
  File "/bot/bot.py", line 7, in <module>
    from cogs.event import set_chatbot
  File "/bot/cogs/event.py", line 13, in <module>
    from src.user_chatbot import get_users_chatbot
  File "/bot/src/user_chatbot.py", line 6, in <module>
    from src.image.image_create import create_image
  File "/bot/src/image/image_create.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
Traceback (most recent call last):
  File "/bot/bot.py", line 7, in <module>
    from cogs.event import set_chatbot
  File "/bot/cogs/event.py", line 13, in <module>
    from src.user_chatbot import get_users_chatbot
  File "/bot/src/user_chatbot.py", line 6, in <module>
    from src.image.image_create import create_image
  File "/bot/src/image/image_create.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
Traceback (most recent call last):
  File "/bot/bot.py", line 7, in <module>
    from cogs.event import set_chatbot
  File "/bot/cogs/event.py", line 13, in <module>
    from src.user_chatbot import get_users_chatbot
  File "/bot/src/user_chatbot.py", line 6, in <module>
    from src.image.image_create import create_image
  File "/bot/src/image/image_create.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by xXG0DLessXx** [comment]
I seem to have fixed it. 
`Pillow==8.1.0`
Was missing in the requirements.txt and i had to provide new cookies. Now works.

**Comment by xXG0DLessXx** [comment]
New error, I now get
`Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.bing.com/images/kblob')`

When trying to chat... but at least image creation is working.

**Comment by xXG0DLessXx** [comment]
Addendum to the above: It seems as soon as I try to switch style I get the above error. Balanced style seems to work.

**Comment by FuseFairy** [comment]
> New error, I now get `Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.bing.com/images/kblob')`
> 
> When trying to chat... but at least image creation is working.

Please try this code for me if you can, because I'm not sure what's causing it.
`pip install sydney-py`

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/3d4b6c4b-36ff-4706-b189-9d043572de4b)

```
import asyncio

from sydney import SydneyClient

cookies = "Input header string"

async def main() -> None:
    async with SydneyClient(style="creative", bing_cookies=cookies) as sydney:
        while True:
            prompt = input("You: ")

            if prompt == "!reset":
                await sydney.reset_conversation()
                continue
            elif prompt == "!exit":
                break

            print("Sydney: ", end="", flush=True)
            async for response in sydney.ask_stream(prompt):
                print(response, end="", flush=True)
            print("\n")


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by xXG0DLessXx** [comment]
> Try using the latest version, the api has updates, if the error still occurs, it should be a problem with the country of the account, you can try to apply for another country's account, like I am using Taiwan's account.

Sorry for the late reply. Anyway, image gen now works pretty well, and chatting with Bing using the /bing command also works, but trying to continue a conversation, or calling on bing with @ , causes this error: 
<img width="375" alt="image" src="https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/40996215/75c9ca0e-acbc-4ddf-bded-adbb037681a5">

**Comment by FuseFairy** [comment]
"Sorry, I made a mistake; it's zhuang39.
