### ISSUE TITLE
Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.bing.com/images/kblob')

### ISSUE THREAD

**Issue by cauvang32** [FuseFairy/DiscordBot-EdgeGPT#122]
I get this error sometime when using the bot, I usually fix by reset cookies and reset conversation
![Screenshot (1)](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/113093128/fe508a5d-7d0f-46cd-8566-3556f9d0390c)

**Comment by FuseFairy** [comment]
An error occurred while generating an image?

**Comment by cauvang32** [comment]
sorry for late respond but I get this error when using chat but generate image is still good :)

**Comment by agcrisbp** [comment]
> I get the same error when I try to use /bing.
> 
> Also the log shows something else than usual, when using /reset (but in discord it still says "Successfull reset":
> 
> ```
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7f9d5dc6cd50>
> ```

![Screenshot_2024-01-10-00-34-56-454_com termux](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/54905291/359f5b81-e677-43c8-b52b-5f696b6fa066)

+1, it shown when use the /bing command or reply feature.

**Comment by FuseFairy** [comment]
That's strange, I got this error too, but after updating the cookies it worked fine.

**Comment by FuseFairy** [comment]
That's strange, I got this error too, but after updating the cookies it worked fine. So it's an error when sending images?

**Comment by agcrisbp** [comment]
@FuseFairy Nop, it's an error when use the /bing or chat command. The image command works fine.

**Comment by FuseFairy** [comment]
Testing with vpn? I guess is country restriction

**Comment by agcrisbp** [comment]
![Screenshot_2024-01-13-18-56-13-484_com termux](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/54905291/b9a0f0e7-285c-4115-b245-c3bc1b40d39e)

So, I guess its because the Heroku server, I just run the bot on Termux and works fine.

**Comment by cauvang32** [comment]
@FuseFairy hi I saw that reEdgeGPT was updated to v0.0.22 (I think it might  help) so I hope you can update the bot for that update.)

**Comment by FuseFairy** [comment]
Actually, not yet.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/f813f084-d704-42fd-80db-24e3abb591d9)

**Comment by FuseFairy** [comment]
I'll change to use another api
https://github.com/vsakkas/sydney.py

**Comment by FuseFairy** [comment]
> I get this error sometime when using the bot, I usually fix by reset cookies and reset conversation ![Screenshot (1)](https://private-user-images.githubusercontent.com/113093128/294738050-fe508a5d-7d0f-46cd-8566-3556f9d0390c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzMxMTMsIm5iZiI6MTcwNTIzMjgxMywicGF0aCI6Ii8xMTMwOTMxMjgvMjk0NzM4MDUwLWZlNTA4YTVkLTdkMGYtNDZjZC04NTY2LTM1NTZmOWQwMzkwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMTQ2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjAwZjAwZmRmNzNlMzY2NzExNjBlYmQzODVhNjczMmM5NDc3NzdkYWM4YzQ0NDQzMjIyNDNhMjQzOGFlYmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SqlASqwcJ-TQfH4q4rIPdJqPqztEu9ps11zmMUzr_E8)

Is the host you are deploying a local server or a web server?

**Comment by cauvang32** [comment]
Local server :))

**Comment by cauvang32** [comment]
Can add proxy setting and suggest for me some sock5 proxy?

**Comment by FuseFairy** [comment]
open src\user_chatbot.py line 37, make changes as shown, and try to use `/bing` again

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/342b3cf2-c72e-422d-8eca-921adfe4274c)

**Comment by cauvang32** [comment]
Thanks and sorry for my mistake, the v0.0.22 was in Dev not for use now:)

**Comment by FuseFairy** [comment]
It's fine, so can you successfully get a response using a proxy?

**Comment by cauvang32** [comment]
I am deploy my bot now wait me for a while
