### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by herowarriors0** [FuseFairy/DiscordBot-EdgeGPT#123]
There is another post for /chat not working, but today for some reason when using /create-image it says Error: 'NoneType' object is not iterable. I restarted the bot several times, and I updated the cookies but it still doesn't work.

**Comment by estrizal** [comment]
Yeah. I had a similar issue. Re_edge_gpt's image generation stops working for some reason if you run it on the same machine for a l long time. 

I changed my hosting. and it started to generate images once again like normal. but after 8 days. Now it has once again stopped working. If I run the code on my PC. it works. if I run the same code on the VM I am hosting, I get "NoneType" error.

**Comment by FuseFairy** [comment]
Maybe some countries seem to have restrictions, not sure yet.
