### ISSUE TITLE
i can't run the code 

### ISSUE THREAD

**Issue by GasmiAbdou** [FuseFairy/DiscordBot-EdgeGPT#125]
i installed all requirements and when i did python bot.py i got this in VSC : 

PS C:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main>  c:; cd 'c:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main'; & 'C:\Users\MSI-PC\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\MSI-PC\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '56240' '--' 'c:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\bot.py' 
Traceback (most recent call last):
  File "c:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\bot.py", line 7, in <module>
    from cogs.event import set_chatbot
  File "c:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\cogs\event.py", line 12, in <module>
    from src import log
ImportError: cannot import name 'log' from 'src' (C:\Users\MSI-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\src\__init__.py)
PS C:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main>

**Comment by FuseFairy** [comment]
Change cogs\event.py line12 -> `from src.log import setup_logger`

**Comment by GasmiAbdou** [comment]
@FuseFairy Traceback (most recent call last):
  File "c:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\bot.py", line 7, in <module>
    from cogs.event import set_chatbot
  File "c:\Users\MSI-PC\Downloads\DiscordBot-EdgeGPT-main\DiscordBot-EdgeGPT-main\cogs\event.py", line 12, in <module>
    from src.log import setup_logger
ModuleNotFoundError: No module named 'src.log'
stilll

**Comment by FuseFairy** [comment]
Strange, because src\log.py exists

**Comment by FuseFairy** [comment]
try this `from ..src.log import setup_logger`

**Comment by FuseFairy** [comment]
use this commad to run bot: `python -m bot`

**Comment by FuseFairy** [comment]
It's a relative path problem, please change the code like this

```python
import sys
import os
source = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, '../src')
from src.log import setup_logger
```

**Comment by GasmiAbdou** [comment]
support server plz @FuseFairy

**Comment by FuseFairy** [comment]
@GasmiAbdou Try using Docker to run the bot

**Comment by GasmiAbdou** [comment]
@FuseFairy try to run it on replit and see the issue  there s a bug !! broo

**Comment by FuseFairy** [comment]
Create an empty __init__.py file in the src folder and it will run fine.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/59780362-9ecf-4179-ba3c-d2a5ab329070)
