### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by herowarriors0** [FuseFairy/DiscordBot-EdgeGPT#126]
After I use all 15 of my fast-generate "points" on Bing, it takes much longer to generate an image. For some reason after just 2 minutes it says Error: Request timeouted. I looked into the code, and  I saw 300 seconds, but it still says timeout after just around 2 minutes. Why is that and how can this happen?

**Comment by FuseFairy** [comment]
Is  still request timeouted?

**Comment by FuseFairy** [comment]
was fixed at latest version
