### ISSUE TITLE
Error, help

### ISSUE THREAD

**Issue by Selys-u** [FuseFairy/DiscordBot-EdgeGPT#127]
`>>> **Error: UnauthorizedRequest: Token issued by https://sydney.bing.com/sydney is invalid (IDX10223: Lifetime validation failed. The token is expired. ValidTo (UTC): '1/19/2024 11:58:06 PM', Current time (UTC): '1/20/2024 9:30:04 AM'.)**`

After some time this error appears. Tell me what is causing this and how can I solve it?

**Comment by mcflyru** [comment]
And if you run it via docker compose up, it gives the error `Error: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub?sec_access_token=xlhKRNNiqwrVhp9fPtaQYfosdBcL38QrMoWVeR1HWUQBdURVQRYixBNt94P3b2%2B WYxI2Rzf5Lty9KXlDLKgwoyX2uwRwLyahalBMiyDu7WUYjvBg9ofaRx81LzSnvNP%2Brvh3azPtl0PzD1FeXTodjutw5rhP0XsSf33sDH985TnnkIQ4zLoMiQyBPxZ1W8uxWnr8l1EkK4QcUq53 JcfGUBSUGiUbU2x52qFgw% 2B3TegZztn2DSITMq7bpF3Ykx3oo9wLY2YO6GemGfzeMq6nR6VywSSTuAXWrMNvilDpuWPxRk1iO0xaH6cB10c49Dim619tEOJYr4vYlBuA6yHkzNTz2Ofp6nUIYr76TAyRPN8Ee/24egcdZe clQF9GR39DbtHjjYQXzy7Won2fnZMjLUe9MKpo9YJ5xibhyL5eLAdxpDtaL2CCprFykLCvMciMuvoUnxDpj6v4VeFdGNN10%2BLUzFtb3opIy3mqufTGjuEX3XRJEIhua4aZ4fFXvGpmkEvPHk0iPPdYa 51usiwRLPpnkWuIU1WGs%2BZUCS4effQSdt09SzBSjvY6IhV1jOBs2qqvup7kvCIkkR5ey8%2BlWRd2RI4Qg6wYaHkT08/O/IY%2BBeEm7xZaSSZke%2B9q4niKmomDl/ioJaB42bLDynxyZqw dyQYh4CwQjVbmTLdPWZqVpU7F2qws6uC03sLUU%2BqpMIEPgetxlpi0NiNNWe5ct/OZPOIxsYiJ0hdTvS0uMrMNK/qlWfbkbq9nbVI/lLaouSbuwVVgYScYH/fK5RyveqhZKHLRF3AtKfMeV/vxM qTn64Jd0ymmSWEbKaZEwlpn6tLRLR4h74b8uOJ12DyTg3sviPYrpSRwA75hM0f855WQ6VdVMsFdQYng/ciSsNvKKOXXwVEcTJL8f%2B5PoSfxE3C%2B4rRik6fABoHEZIuOnwO1fMaT1UG6CS zx2qZQwjn19omfywxdK3ATdHQ8qAxvpLZDegXo6KT1Gs1qYJQbnAP40oo%2BXcUdTlSteSgwghA64zngwRiQ2m4DOH0r7E2nLxEBayT8o0cKPsASB8qeu088b1ufvrI2BvRL1KKk8llyovOS l1Qc5O7qo4lKRXyUEVORO2WyYyg7mY8seDWLzhDqXM6kaX/q11DKqilfoNTOLHhFwCZFwuFq2%2BNXK4Trz%2BA%3D%3D' )`

**Comment by FuseFairy** [comment]
> The token is expired

Bing block your connect, Try to clear cookie .

**Comment by mcflyru** [comment]
Regarding the first messageю, after restarting the bot everything works

Doesn't work at all via docker

**Comment by mcflyru** [comment]
I launched it on another machine in Germany via Docker, it worked, but when using python without Docker it stopped working. But the error 'UnauthorizedRequest: Token issued by https://sydney.bing.com/sydney is invalid (IDX10223: Lifetime validation failed. The token is expired. ValidTo (UTC): '1/20/2024 7:32:01 PM ', Current time (UTC): '1/20/2024 8:09:13 PM'.)' remained so((((((

**Comment by FuseFairy** [comment]
Maybe use another account

**Comment by mcflyru** [comment]
I'll definitely try it, thanks. For now, using a crutch, I restart Docker through the tg bot

**Comment by mcflyru** [comment]
> Maybe use another account

The strange thing is that I don’t change the cookies, just restarting the bot helps me

**Comment by mcflyru** [comment]
Any ideas why restarting the bot helps?

**Comment by mcflyru** [comment]
maybe it really has something to do with time synchronization? On the machine itself everything seems to be ok

**Comment by FuseFairy** [comment]
So on initial startup, the bot will give an error, which can be fixed after a restart.

**Comment by Selys-u** [comment]
No, the bot works when launched, after some time the bot throws an error on any request. Restarting fixes this error

**Comment by FuseFairy** [comment]
Is it possible that too many people are using this cookie?

**Comment by Selys-u** [comment]
Well, this is my account, so no. I only use it in the bot at the moment

**Comment by Selys-u** [comment]
'm not sure yet, but if I use it, everything seems to be fine. And if it is “idle” for some time, it stops working

**Comment by FuseFairy** [comment]
Try using the latest version, the api has updates
