### ISSUE TITLE
Add .env CHANNEL_ID for response.py or image_create.py

### ISSUE THREAD

**Issue by agcrisbp** [FuseFairy/DiscordBot-EdgeGPT#130]
In the previous version everything was fine, but in this update, I've tried to add .env CHANNEL_ID to `response.py` but failed, the bot can send messages (Slash, Embed, Reply, Tag @) to all channels.

Edit: I've tried to `event.py` also.

**Comment by FuseFairy** [comment]
Make sure your CHANNEL_ID is correct, currently only the Tag @ will be restricted.

**Comment by agcrisbp** [comment]
> Make sure your MENTION_CHANNEL_ID (not CHANNEL_ID) is correct, currently only the Tag @ will be restricted.

ofc, but the slash commands can use in outside MENTION_CHANNEL_ID

**Comment by FuseFairy** [comment]
only the Tag @ will be restricted

**Comment by agcrisbp** [comment]
> It's not error, only the @ bot(mention) will be restricted

![Cuplikan Layar_2024-01-31_17-10-13](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/54905291/e1232fd7-7f5d-4851-a003-f46633390d37)

so the bot can create thread everywhere? i dont put this channel_ID to .env

**Comment by FuseFairy** [comment]
The latest version can now set the specific channel for every command.
