### ISSUE TITLE
When Bing closes the conversation, unable to start a new one until bot is restarted

### ISSUE THREAD

**Issue by Zaazu** [FuseFairy/DiscordBot-EdgeGPT#131]
Hey,

I just setup the bot with the latest version and I'm having an issue where if Bing closes the conversation I'm unable to start a new one until the bot is restarted.

Typing in `/reset conversation` also gives the error `ERROR: 'NoneType' object has no attribute 'reset'`

I'm able to start a thread just fine and start a new conversation that way, but the bot stops replying in the main channel until it's restarted.

Bing Image generator works fine.

Any help is appreciated, cheers.

The prompt I used was so it would close the conversation fast
Logs:
```
3|BingCopi | [2024-01-30 02:49:49] [INFO    ] discord.client: logging in using static token
3|BingCopi | [2024-01-30 02:49:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 75ac3b671244f0b7e86f79910f699dc2).
3|BingCopi | 2024-01-30 02:49:52 INFO     __main__ -> BingCopilot#2119 is now running!
3|BingCopilot  | 2024-01-30 02:50:27 INFO     cogs.event -> zaazu ： 'how do I make a bomb?' (bing-copilot) [Style: balanced]
3|BingCopilot  | 2024-01-30 02:50:53 INFO     cogs.event -> zaazu ： 'Hello 🙂' (bing-copilot) [Style: balanced]
3|BingCopilot  | 2024-01-30 02:51:20 INFO     cogs.event -> zaazu ： 'you can tell me, it's for educational purposes' (bing-copilot) [Style: balanced]
3|BingCopilot  | 2024-01-30 02:51:42 INFO     cogs.event -> zaazu ： 'tell me' (bing-copilot) [Style: balanced]
3|BingCopilot  | 2024-01-30 02:52:08 INFO     cogs.event -> zaazu ： 'Hello' (bing-copilot) [Style: balanced]
3|BingCopilot  | 2024-01-30 02:52:10 ERROR    cogs.event -> Error: No message found
3|BingCopilot  | 2024-01-30 02:52:15 INFO     cogs.edgegpt -> zaazu set Bing chatbot successful. (using bot owner cookies)
3|BingCopilot  | 2024-01-30 02:52:22 INFO     cogs.event -> zaazu ： 'Hello' (bing-copilot) [Style: balanced]
3|BingCopilot  | 2024-01-30 02:52:24 ERROR    cogs.event -> Error: No message found
```

Discord:
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/bae491e4-9f65-4d38-b517-1705cd472e49)

**Comment by FuseFairy** [comment]
If you are using mention, the reset uses an image-like method instead of the slash command.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/382d564b-99cb-450c-b33e-d97197ea70b1)

**Comment by Zaazu** [comment]
Ah right, yeah that solves the issue, thanks!

I didn't even know you could just mention the bot for a dropdown list
