### ISSUE TITLE
Image request timed out

### ISSUE THREAD

**Issue by Zaazu** [FuseFairy/DiscordBot-EdgeGPT#132]
Hi,

Since running out of fast gens, the image requests are timing out despite eventually completing when I check the image generator gallery. Is there any way to increase the time before the bot times out?

Cheers

Discord:
![Screenshot 2024-01-30 191705](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/adef8580-1270-45d6-9d9b-9abcd16afc55)

Bing Image Gen:
![Screenshot 2024-01-30 191646](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/d99b2608-cd29-4d1b-b68a-408d407aa01c)
![Screenshot 2024-01-30 191641](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/32438104-49e4-40f0-8703-dd7a3798056a)

edit: Just noticed someone else was having a similar issue (#126). The bot definitely doesn't take 5 min to timeout, it's much shorter:

```
3|BingCopi | 2024-01-30 19:10:02 INFO     src.image.image_create -> zaazu ： 'wolf howling at the moon, abstract art, vibrant colors, painted style' (bing-copilot) [BingImageCreator]
3|BingCopi | 2024-01-30 19:11:09 ERROR    src.image.image_create -> Error while create image: Request timed out.
3|BingCopi | 2024-01-30 19:11:34 WARNING  cogs.event -> Bing has been successfully reset
3|BingCopi | 2024-01-30 19:12:09 INFO     src.image.image_create -> zaazu ： 'wolf howling at the moon, abstract art, vibrant colors, painted style' (bing-copilot) [BingImageCreator]
3|BingCopi | 2024-01-30 19:13:18 ERROR    src.image.image_create -> Error while create image: Request timed out.
```

I increased the timeout to 600, and it times out in about a minute:
```
3|BingCopi | 2024-01-30 20:28:01 INFO     src.image.image_create -> zaazu ： 'close-up Wolf caricature drawing, exaggerated features, realistic textures, humor-infused, playful' (bing-copilot) [BingImageCreator]
3|BingCopi | 2024-01-30 20:29:08 ERROR    src.image.image_create -> Error while create image: Request timed out.
```

**Comment by FuseFairy** [comment]
I'm not sure, but try add `max_generate_time_sec`.
```python
images = await async_gen.get_images(prompt=prompt, timeout=300, max_generate_time_sec=300)
```

**Comment by Zaazu** [comment]
I'll give that a go and have to let you know tomorrow, since the images aren't taking that long to generate due to it not being peak time I'm guessing, cheers

**Comment by Zaazu** [comment]
No timeouts today, looks fixed, cheers
