### ISSUE TITLE
Error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Zaazu** [FuseFairy/DiscordBot-EdgeGPT#133]
I'm getting a lot of `Error: 'NoneType' object is not iterable` when trying to generate an image, it's been stuck like this for about 12 hours. Bing chat works fine.

I've restarted the bot, refreshed the cookie and checked there's not an image being generated.

I've updated to the latest version and still getting the same error.

Thanks

```
3|BingCopilot  | 2024-02-02 18:09:22 INFO     cogs.edgegpt -> zaazu set Bing chatbot successful. (using bot owner cookies)
3|BingCopilot  | 2024-02-02 18:09:22 INFO     src.image.image_create -> zaazu ： 'a bee' (bing-copilot) [BingImageCreator]
3|BingCopilot  | Image create failed pls check cookie or old image still creating
3|BingCopilot  | 2024-02-02 18:09:23 ERROR    src.image.image_create -> Error while create image: 'NoneType' object is not iterable
3|BingCopilot  | 2024-02-02 18:09:44 INFO     cogs.event -> zaazu ： 'Hello' (bing-copilot) [Style: balanced]
```

**Comment by Zaazu** [comment]
Set the Microsoft account to Taiwan, or use a VPN?

**Comment by FuseFairy** [comment]
I think just set the Microsoft account to Taiwan, if that doesn't work, try using a VPN to create an account.

**Comment by Zaazu** [comment]
I made a Taiwan account and chat still works but image creation doesn't work still

**Comment by FuseFairy** [comment]
in latest version, make sure your auth_cookie is get from https://bing.com/, or maybe we can go in a Discord, and give me your Taiwan account to help me solve bug.

**Comment by Zaazu** [comment]
On bing.com I don't have a _U. Only on [copilot.microsoft.com](https://copilot.microsoft.com/)

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/8f120707-00a6-4f14-bc26-535b507b54a0)![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/4142cb6a-f936-4898-941c-42c8855e283f)

**Comment by FuseFairy** [comment]
Then look on BingImageCreator's website.

**Comment by Zaazu** [comment]
Still the same
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/b414177f-3910-4e75-9131-54af82847fe2)

**Comment by FuseFairy** [comment]
Are you logged in? and create image on website first, maybe _U will appear

**Comment by Zaazu** [comment]
I'm logged in, still no _U

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/22891753/b7ad285a-3067-426c-962f-82ec6cd32e9e)

**Comment by FuseFairy** [comment]
we can go in a Discord, and give me your Taiwan's account, because it's not likely to happen.

Discord id: zhuang39
