### ISSUE TITLE
Where does the CAPTCHA pop up when the "ERROR: CaptchaChallenge: User needs to solve CAPTCHA to continue." error is being displayed?

### ISSUE THREAD

**Issue by GustavRaispits** [FuseFairy/DiscordBot-EdgeGPT#140]
I tried visiting both https://copilot.microsoft.com/ and https://bing.com/ but no CAPTCHA is being displayed. How can I solve this issue?

![XYnvRwC](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/34628862/1e2f0305-3e7a-4910-86c8-425a6666d030)

I tried your scripts a long time ago as well and got the same issue, I'm currently using the latest version.

UPDATE: Setting the _U value seems to suppress the issue though

**Comment by GustavRaispits** [comment]
> just go to copilot.com, then send a random message and you'll see captcha

Worked! That would be nice to have a command that closes the thread on Discord and clears the Copilot's chat history on https://www.bing.com/

**Comment by GustavRaispits** [comment]
> just go to copilot.com, then send a random message and you'll see captcha

After trying the bot all day with other people it turned out that while the captcha problem can be easily fixed it can also become annoying, sometimes every time a new member starts a conversation I have to complete the captcha, which is not suitable for a bot I plan to keep running 24/7.

I'll consider trying again the bot once you will find a way for suppressing captcha or auto-complete it without having someone to open the browser for completing it every time it pops up. Good luck!

**Comment by FuseFairy** [comment]
Theoretically this won't happen, are you sure you got your cookie from https://copilot.microsoft.com/?
It's not the same as https://www.bing.com/

**Comment by GustavRaispits** [comment]
> Theoretically this won't happen, are you sure you got your cookie from https://copilot.microsoft.com/? It's not the same as https://www.bing.com/

Yeah I'm sure, there are situations where captcha is triggered only to certain users. I told my friend who was getting the captcha error to send a random message on https://copilot.microsoft.com/ but he wasn't getting captcha. I tried to check on my browser if I was able to get the captcha message in some way but still couldn't get it. I tried importing the same cookies I uploaded to the but without results. 

I think that the only way to solve the captcha error is to share my cookies to the members who are getting the issue so they can import the cookies file to their browser and solve it, but it is not optimal since that would mean giving away my account to people.

Unfortunately this script is not really publicly usable due to this issue, the only possible workaround is pushing people to upload their own cookies, but that would be annoying to do since the bot can't handle more than one cookies.json file per user.

**Comment by FuseFairy** [comment]
The temporary solution is to remove the cookies.json file, can still chat with copilot, but the context limit will be shorter.

**Comment by GustavRaispits** [comment]
> The temporary solution is to remove the cookies.json file, can still chat with copilot, but the context limit will be shorter.

Without the cookies.json file the situation is even worse:

![x5bzh0S](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/34628862/d1a45e9b-fdbb-483e-8429-66385689a3a5)
![EcNvAQp](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/34628862/e00cd9ba-341b-426a-8ada-279be6d74c4f)

Without considering the offensive nature of the message my friend sent, the bot keeps displaying the captcha error message to certain members with any message being sent.

Is it possible for coding something that obtains the link of the captcha and outputs it in the bot's console in order to find and solve it?

**Comment by FuseFairy** [comment]
Ok, and do you still get errors when running locally?

**Comment by GustavRaispits** [comment]
> Ok, and do you still get errors when running locally?

My server automatically forwards my IP so technically that wouldn't make any difference, I am able to get the captcha message when I am the one getting the CAPTCHA error, unlike when others get it.

I'm currently pushing my members to use their own cookies file whenever they get the CAPTCHA message error as the only way to go around the issue, which seems to work at the moment.
