### ISSUE TITLE
how to solve this error?

### ISSUE THREAD

**Issue by astrotically** [FuseFairy/DiscordBot-EdgeGPT#143]
i got this error while trying to generate images:

 ERROR    src.image.image_create -> Error while create image：Image create failed pls check cookie or old image still creating
 
 what to do? reply asap!

**Comment by FuseFairy** [comment]
Clean cookies and get again

**Comment by astrotically** [comment]
Error：local variable 'auth_cookie' referenced before assignment

**Comment by FuseFairy** [comment]
are you using the latest version?

**Comment by astrotically** [comment]
i did git pull, i did reset my cookies and it does have "_U" , but the error is still:

ERROR src.image.image_create -> Error while create image：Image create failed pls check cookie or old image still creating

**Comment by FuseFairy** [comment]
I've had this happen before by waiting a bit and then re-fetching the cookies and it's fine

**Comment by astrotically** [comment]
ahh.. alright, hope this issue will be fixed permanently soon
