### ISSUE TITLE
Error "ERROR：'NoneType' object has no attribute 'ask'" whenever I try to type something.

### ISSUE THREAD

**Issue by GustavRaispits** [FuseFairy/DiscordBot-EdgeGPT#145]
Unfortunately this started happening for a while already, even with cookies set. Probably a Bing's site update.

![zLoaj5c](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/34628862/44410b4c-95ef-4836-af23-8780d28bf8e3)

**Comment by FuseFairy** [comment]
try new version [v1.1.4](https://github.com/FuseFairy/DiscordBot-EdgeGPT/releases/tag/v1.1.4)

**Comment by GustavRaispits** [comment]
> try new version [v1.1.4](https://github.com/FuseFairy/DiscordBot-EdgeGPT/releases/tag/v1.1.4)

I've already tried version 1.1.4, even tried to do a fresh install some minutes ago, no difference.

**Comment by FuseFairy** [comment]
This is not a code problem.

## Possible solutions:
1. Try using a Microsoft account from another country.
2. Try using a VPN.

**Comment by GustavRaispits** [comment]
> This is not a code problem.
> 
> ## Possible solutions:
> 1. Try using a Microsoft account from another country.
> 2. Try using a VPN.

I've been trying to use copilot with a VPN without any result, I've even tried to run the script on another pc with Python 3.11.5.

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\copilot\DiscordBot-EdgeGPT\src\bing_chat\response.py", line 78, in send_message
    reply = await chatbot.ask(
                  ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ask'

I currently don't have a Microsoft account from another country, the bot was working perfectly with my account as well until I didn't open this report.

**Comment by FuseFairy** [comment]
try latest response.py code
https://github.com/FuseFairy/DiscordBot-EdgeGPT/blob/main/src/bing_chat/response.py

**Comment by GustavRaispits** [comment]
> try latest response.py code https://github.com/FuseFairy/DiscordBot-EdgeGPT/blob/main/src/bing_chat/response.py

Tried it on a fresh install, I'm getting the same exact issue.
![7SDZ6FK](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/34628862/d6853d0d-c350-4e80-98c1-ea40b97b25f0)

**Comment by FuseFairy** [comment]
strange, try run with Replit.

https://replit.com/@dd8611706/DiscordBot-EdgeGPT

**Comment by GustavRaispits** [comment]
> strange, try run with Replit.
> 
> https://replit.com/@dd8611706/DiscordBot-EdgeGPT

Hello, works with replit after setting cookies.

When I run the script on my machine and set my cookies as well, I get this issue:

![2OkNKXt](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/34628862/5e4e05bf-3a87-473c-8d14-83892d2e6988)

Instead of using Python version 3.10 I'll try to use the same python version as Replit uses, I'll update you soon.

**Comment by FuseFairy** [comment]
I think you should try to run it on Replit first, if it works then it's basically a problem with your local environment.

**Comment by FuseFairy** [comment]
I think you should try to run it on Replit first, if it works then it's basically a problem with your local environment.

In Replit, set your cookies like this:
step1 -> get cookies 
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/26ff9609-2212-4019-b4a4-f44816742b73)

step2 -> Paste directly into secrets
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/ee4320a9-16a3-4e69-baef-1dc9e46b229b)

**Comment by FuseFairy** [comment]
I think it's not the python version problem.
You can use `!upload` command to upload cookies directly instead of setting cookies.json file.
