### ISSUE TITLE
Image generation aswell as chat function is not working.

### ISSUE THREAD

**Issue by unambition** [FuseFairy/DiscordBot-EdgeGPT#147]
Image generation aswell as chat function is not working.

Image generation: Error：[Errno 11001] getaddrinfo failed

Chat function: ERROR：Cannot connect to host www.bing.com:443 ssl:default [getaddrinfo failed]

**Comment by FuseFairy** [comment]
Looks like an internet connection problem. Maybe try running it on Replit and see if it works.

**Comment by FuseFairy** [comment]
try run with Replit.

https://replit.com/@dd8611706/DiscordBot-EdgeGPT

**Comment by FuseFairy** [comment]
> > попробуй запустить через Replit.
> > https://replit.com/@dd8611706/DiscordBot-EdgeGPT
> 
> I also have a problem with pictures, and this site that you provided as an example does not work in my country, so I can’t check for sure

maybe country problem? try vpn
and make sure your account can generate images on BingImageCreator website
