### ISSUE TITLE
Error：Image create failed pls check cookie or old image still creating

### ISSUE THREAD

**Issue by NikoPancetta** [FuseFairy/DiscordBot-EdgeGPT#155]
When I implemented the bot, everything was working great, after about 2-3 months, now the following error occurs: “Error：Image create failed pls check cookie or old image still creating” , when I use the /create image command. Copilot works perfectly, except for the error when I press the quick replies button, but I'm fine with that too.

**Comment by FuseFairy** [comment]
Working fine now;  Maybe their service is down, like today.

**Comment by NikoPancetta** [comment]
> Working fine now; Maybe their service is down, like today.



> Working fine now; Maybe their service is down, like today.

I solved it by opening the updated GIT directly from Replit. I was using an old version.


When I use Copilot private, it tells me I don't have access to the link. 
Also I wanted to know if it was possible to implement a system of logging the various users into the server, so they can use their own account and not mine.

**Comment by FuseFairy** [comment]
have any error messages when you using Copilot private?

and this command can let users use their own account.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/78064680/a5d5a3fc-3fe9-46be-8288-1e732208b79b)

**Comment by NikoPancetta** [comment]
I don't get any errors. Just the message that I don't have access to the link directly from Discord

**Comment by FuseFairy** [comment]
Maybe you didn't give the bot access to the private thread.
