### ISSUE TITLE
 Error：Upload image failed

### ISSUE THREAD

**Issue by cauvang32** [FuseFairy/DiscordBot-EdgeGPT#156]
Yeah but I didn't request to get a image, I just ping the bot and say "hi" then it show this error.
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/113093128/6d13750d-f167-42c4-947e-6446a47ba36a)
Console log:
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/113093128/c5f25548-491f-46df-b4f7-e00082f677a3)
What I had done:
- Use new cookie from both bing and copilot.
- Reset conversation.

**Comment by cauvang32** [comment]
@FuseFairy

**Comment by FuseFairy** [comment]
Is that working fine in Thread?

**Comment by cauvang32** [comment]
Yeah it not working in theard too

**Comment by cauvang32** [comment]
Update: after reset all the thing, I get this error:
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/113093128/38483907-b61f-4e30-ba34-4bcc3bebfdaa)

**Comment by cauvang32** [comment]
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/113093128/d9d95604-9167-47a2-a8cd-a9020c13a4b3)

**Comment by FuseFairy** [comment]
Will fix it next week, I'm currently inconvenient abroad, thanks for reporting the bug

**Comment by cauvang32** [comment]
Thank for your support:)
