### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by astrotically** [FuseFairy/DiscordBot-EdgeGPT#159]
I tried using chatbot and it showed me this:

**ERROR：InternalError: Error calling extension "JailBreak Filter" (jailbreak-filter) 
Full exception: {'type': 2, 'invocationId': '3', 'item': {'firstNewMessageIndex': None, 'defaultChatName': None, 'conversationId': '51D|BingProd|E9D8D1CD6542F375B2DAD496C1509B5B7890CCC0E1EBEE915AC469FA6B810BB1', 'requestId': '7f299a30-b661-4079-b42f-c3d324d6b533', 'telemetry': {'startTime': '2024-09-26T17:25:03.5254136Z', 'userMessageRequestStartTime': None}, 'result': {'value': 'InternalError', 'message': 'Error calling extension "JailBreak Filter" (jailbreak-filter)', 'error': 'Error calling extension "JailBreak Filter" (jailbreak-filter)', 'serviceVersion': '20240925.191'}}}**

What should I do?

**Comment by FuseFairy** [comment]
jailbreak is temporarily disabled. Don't use it yet.

**Comment by astrotically** [comment]
Thanks for the solution, but can this run on pebblehost?
