### ISSUE TITLE
Getting "The application did not respond"

### ISSUE THREAD

**Issue by rikuddo91** [FuseFairy/DiscordBot-EdgeGPT#2]
Using Python 3.8 and 3.11 (on separate machines). Every installed correctly and the bot is showing running,

```
Bot is Up and Ready!
Synced 2 commands 
```
But when I use /chat command, it only returns 'The application did not respond'.

---

Got it working. It wasn't /chat (message) but /bing (message) command that worked for me.

**Comment by hello-navi** [comment]
(Oops, didn't mean to reference this.)
