### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by VIDRA4444** [FuseFairy/DiscordBot-EdgeGPT#23]
Hello! I have this trace when I start up, but everything is installed according to the instructions. What can it be? ==== RESTART: C:\Users\1111\Desktop\DiscordBot-EdgeGPT-main\bot.py ====
Traceback (most recent call last):
  File "C:\Users\1111\Desktop\DiscordBot-EdgeGPT-main\bot.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
>>>

**Comment by VIDRA4444** [comment]
Okay, I figured it out and installed the discord.py library, now the error is different: [30;1m2023-03-23 01:55:54[0m [31mERROR [0m [35m__main__[0m -> discord.py version 2.2.2 is installed but does not match the requirements

**Comment by tankow79** [comment]
Hi there was an error during startup:

discord.client logging in using static token
Traceback (most recent call last):
  File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "D:\Users\AndraX\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\AndraX\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 746, in start
    await self.connect(reconnect=reconnect)
  File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 672, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
python-BaseException

I tried switching the dependency as mentioned in "discord.errors.PrivilegedIntentsRequired" but it doesn't work for me

**Comment by tankow79** [comment]
@VIDRA4444 You need to install the version of the library specified in requirements.txt "pip install -r requirements.txt"

In your case, you need to remove the discord.py version 2.2.2 library "pip uninstall discord.py" and then install discord.py version 2.1.0 "pip install discord.py==2.1.0"

**Comment by FuseFairy** [comment]
> Hi there was an error during startup:
> 
> discord.client logging in using static token
> Traceback (most recent call last):
>   File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 828, in run
>     asyncio.run(runner())
>   File "D:\Users\AndraX\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "D:\Users\AndraX\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 817, in runner
>     await self.start(token, reconnect=reconnect)
>   File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 746, in start
>     await self.connect(reconnect=reconnect)
>   File "D:\Programs_for_python\DiscordBot-EdgeGPT-main\venv\lib\site-packages\discord\client.py", line 672, in connect
>     raise PrivilegedIntentsRequired(exc.shard_id) from None
> discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
> python-BaseException
> 
> I tried switching the dependency as mentioned in "discord.errors.PrivilegedIntentsRequired" but it doesn't work for me

https://github.com/FuseFairy/DiscordBot-EdgeGPT/issues/19#issuecomment-1475361611

Here is the solution.

**Comment by VIDRA4444** [comment]
> @VIDRA4444 You need to install the version of the library specified in requirements.txt "pip install -r requirements.txt"
> 
> In your case, you need to remove the discord.py version 2.2.2 library "pip uninstall discord.py" and then install discord.py version 2.1.0 "pip install discord.py==2.1.0"

Having done as you said, I got this error: [30;1m2023-03-23 13:39:27[0m [31mERROR [0m [35m__main__[0m -> python-dotenv version 1.0.0 is installed but does not match the requiremen

**Comment by VIDRA4444** [comment]
Oh my God, I'm already tired... I installed the correct version of dotenv, but a new error popped up...  
File "C:\Users\1111\Desktop\bot\DiscordBot-EdgeGPT-main\bot.py", line 9, in <module>
    load_dotenv()
TypeError: load_dotenv() missing 1 required positional argument: 'dotenv_path'

**Comment by VIDRA4444** [comment]
yes. file is .env

**Comment by FuseFairy** [comment]
I update repo, you can try again.

**Comment by VIDRA4444** [comment]
> I update repo, you can try again.

Do I need to reinstall the zip?

**Comment by FuseFairy** [comment]
Yes

**Comment by VIDRA4444** [comment]
Aaaaand...... 
![image](https://user-images.githubusercontent.com/128645600/227183768-18140e16-60bc-4107-a080-ce0bcd65147c.png)

**Comment by VIDRA4444** [comment]
;(

**Comment by FuseFairy** [comment]
well,I guess you should change load_dotenv to load_dotenv(dotenv_path= input_your_.env_path)

**Comment by VIDRA4444** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/128645600/227185648-27aa9239-1fbe-4b17-bf7c-d8beda1b7382.png)

**Comment by VIDRA4444** [comment]
I'm sorry if I'm dumb. I don't understand much about code.

**Comment by FuseFairy** [comment]
> Like this? ![image](https://user-images.githubusercontent.com/128645600/227185648-27aa9239-1fbe-4b17-bf7c-d8beda1b7382.png)

yes, but is dotenv_path="your_path"

**Comment by VIDRA4444** [comment]
> 

Warning (from warnings module):
  File "C:\Users\1111\AppData\Local\Programs\Python\Python310\lib\site-packages\dotenv.py", line 18
    warnings.warn("can't read %s - it doesn't exist." % dotenv_path)
UserWarning: can't read C:Users\1111\AppData\Local\Programs\Python\Python310\Lib\site-packages\dotenv\.env - it doesn't exist.
[30;1m2023-03-23 15:19:05[0m [31mERROR   [0m [35m__main__[0m -> discord.py version 2.1.0 is installed but does not match the requirements

**Comment by FuseFairy** [comment]
> > 
> 
> Warning (from warnings module): File "C:\Users\1111\AppData\Local\Programs\Python\Python310\lib\site-packages\dotenv.py", line 18 warnings.warn("can't read %s - it doesn't exist." % dotenv_path) UserWarning: can't read C:Users\1111\AppData\Local\Programs\Python\Python310\Lib\site-packages\dotenv.env - it doesn't exist. �[30;1m2023-03-23 15:19:05�[0m �[31mERROR �[0m �[35m__main__�[0m -> discord.py version 2.1.0 is installed but does not match the requirements

I updated the version of discord.py to 2.2.2 and you can see the change in requirements.txt.

**Comment by VIDRA4444** [comment]
okay! [30;1m2023-03-23 15:28:40[0m [31mERROR   [0m [35m__main__[0m -> python-dotenv version 0.2.0 is installed but does not match the requirements

**Comment by FuseFairy** [comment]
Okay, I know what I should fix

**Comment by FuseFairy** [comment]
Modify your bot.py code to look like this

```
import discord
import os
import src.log
from discord.ext import commands
from dotenv import load_dotenv

load_dotenv(dotenv_path="./.env")

bot = commands.Bot(command_prefix='!', intents = discord.Intents.all())

# init loggger
logger = src.log.setup_logger(__name__)

@bot.event
async def on_ready():
    logger.info(f'{bot.user} is now running!')
    for Filename in os.listdir('./cogs'):
        if Filename.endswith('.py'):
            await bot.load_extension(f'cogs.{Filename[:-3]}')  
    print("Bot is Up and Ready!")
    try:
        synced = await bot.tree.sync()
        print(f"Synced {len(synced)} commands")
    except Exception as e:
        print(e)
        
@bot.command()
async def load(ctx, extension):
    await bot.load_extension(f'cogs.{extension}')
    await ctx.send(f'Loaded {extension} done.')

@bot.command()
async def unload(ctx, extension):
    await bot.unload_extension(f'cogs.{extension}')
    await ctx.send(f'Un-Loaded {extension} done.')

@bot.command()
async def reload(ctx, extension):
    await bot.reload_extension(f'cogs.{extension}')
    await ctx.send(f'Re-Loaded {extension} done.')

@bot.command()
async def clean(ctx):
    open('discord_bot.log', 'w').close()
    await ctx.send(f'Has been emptied')

if __name__ == '__main__':
    bot.run(os.getenv("DISCORD_BOT_TOKEN"))
```

**Comment by VIDRA4444** [comment]
hm... 
![image](https://user-images.githubusercontent.com/128645600/227192118-b30fbb03-1a94-4e3b-9a72-9cdb33cb699d.png)

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227193259-cf50e667-b150-47bf-9e9c-9a50ddd60f1c.png)

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227195224-2c4f1b1f-63e6-42d5-b975-48f924af577b.png)

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227195466-27e3a8d4-3746-4d7a-836e-f9e66ef69952.png)
damn! the bot is working, although previously it was not even online

**Comment by FuseFairy** [comment]
: )

**Comment by VIDRA4444** [comment]
but........ 
![image](https://user-images.githubusercontent.com/128645600/227195687-d5732c53-d518-4fd8-a432-76a6d64dcc06.png)

**Comment by VIDRA4444** [comment]
no response

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227196073-532c0759-9ffc-4e4d-87dc-96a88593eeb1.png)

**Comment by VIDRA4444** [comment]
he's online, but there are a lot of errors and he doesn't respond to any commands

**Comment by VIDRA4444** [comment]
yes

**Comment by VIDRA4444** [comment]
Okay and... what should I do?

**Comment by FuseFairy** [comment]
confirm your edgegpt package info, like this:

```
(py_3-9-16) C:\Users\dd861\pyhon\discord bot EdgeGPT>pip show EdgeGPT
Name: EdgeGPT
Version: 0.1.3
Summary: Reverse engineered Edge Chat API
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: c:\users\dd861\anaconda3\envs\py_3-9-16\lib\site-packages
Requires: asyncio, certifi, httpx, prompt-toolkit, regex, requests, rich, websockets
Required-by:
```

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227198750-c885950d-da58-4dbe-96a6-b3ff35f06a8a.png)

**Comment by FuseFairy** [comment]
This seems to be  no problem, hm...

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227199464-c8e447ed-7ded-41ec-8d69-a1d78dc9e919.png)
Here are the current startup errors

**Comment by FuseFairy** [comment]
Mybe you can reinstall all package, and try again

**Comment by VIDRA4444** [comment]
All packages??? Python, dotenv, edge?

**Comment by VIDRA4444** [comment]
> okay! �[30;1m2023-03-23 15:28:40�[0m �[31mERROR �[0m �[35m__main__�[0m -> python-dotenv version 0.2.0 is installed but does not match the requirements

Are you sure the error is not in the code? Last time I had an error only with dotenv, but now the whole screen is red

**Comment by FuseFairy** [comment]
Then try to install  python-dotenv latest version first

**Comment by FuseFairy** [comment]
https://github.com/yaml/pyyaml/issues/574

you should try this

**Comment by FuseFairy** [comment]
I think this is a problem with py3.10, because I don't have this error with py3.9.

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227202605-d0a516be-eada-475d-9bac-f0d153867b06.png)

**Comment by VIDRA4444** [comment]
Something new...

**Comment by FuseFairy** [comment]
Have you set the ``cookies.json`` file?

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227203463-b1c6e31a-b18b-4905-9e06-8cee1063ac95.png)
yes

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227205946-f31c06c2-e169-47c0-bb8c-a228e0adf0ea.png)
I put in a new cookie, nothing has changed

**Comment by VIDRA4444** [comment]
Can you send a previous version of the code?

**Comment by VIDRA4444** [comment]
I know, I need a previous version of it, before the one you recently fixed.

**Comment by FuseFairy** [comment]
```
import discord
import os
import src.log
import sys
import pkg_resources
from discord.ext import commands
from dotenv import load_dotenv

load_dotenv()

bot = commands.Bot(command_prefix='!', intents = discord.Intents.all())

# init loggger
logger = src.log.setup_logger(__name__)

def check_verion() -> None:
    # Read the requirements.txt file and add each line to a list
    with open('requirements.txt') as f:
        required = f.read().splitlines()

    # For each library listed in requirements.txt, check if the corresponding version is installed
    for package in required:
        # Use the pkg_resources library to get information about the installed version of the library
        package_name, package_verion = package.split('==')
        installed = pkg_resources.get_distribution(package_name)
        # Extract the library name and version number
        name, version = installed.project_name, installed.version
        # Compare the version number to see if it matches the one in requirements.txt
        if package != f'{name}=={version}':
            logger.error(f'{name} version {version} is installed but does not match the requirements')
            sys.exit()

@bot.event
async def on_ready():
    logger.info(f'{bot.user} is now running!')
    for Filename in os.listdir('./cogs'):
        if Filename.endswith('.py'):
            await bot.load_extension(f'cogs.{Filename[:-3]}')  
    print("Bot is Up and Ready!")
    try:
        synced = await bot.tree.sync()
        print(f"Synced {len(synced)} commands")
    except Exception as e:
        print(e)
        
@bot.command()
async def load(ctx, extension):
    await bot.load_extension(f'cogs.{extension}')
    await ctx.send(f'Loaded {extension} done.')

@bot.command()
async def unload(ctx, extension):
    await bot.unload_extension(f'cogs.{extension}')
    await ctx.send(f'Un-Loaded {extension} done.')

@bot.command()
async def reload(ctx, extension):
    await bot.reload_extension(f'cogs.{extension}')
    await ctx.send(f'Re-Loaded {extension} done.')

@bot.command()
async def clean(ctx):
    open('discord_bot.log', 'w').close()
    await ctx.send(f'Has been emptied')

if __name__ == '__main__':
    check_verion()
    bot.run(os.getenv("DISCORD_BOT_TOKEN"))
```

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227207807-e3dbd523-d3c1-4e3d-bbd2-d4637ea430db.png)
The only error

**Comment by VIDRA4444** [comment]
Do you know what you can do about it? The requirements state that doten should be 0.20.0, but the code asks for 1.0

**Comment by FuseFairy** [comment]
modify requirements.txt:
```
discord.py==2.2.2
python-dotenv==1.0.0
PyYAML==6.0
EdgeGPT==0.1.3
```

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227208835-46980848-efc3-4d4b-87f9-757507b1a959.png)

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227209638-3f4a612f-e1f5-49ac-9bc0-e36bd0478ec3.png)
New error!

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227209999-cd913a94-818d-481e-ae45-fe67e7170a4b.png)
code

**Comment by VIDRA4444** [comment]
same error

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227211661-5f2f65e9-4d1b-4fdf-9fee-dc1a6292908f.png)
Yea! New error...

**Comment by FuseFairy** [comment]
same, modify requirements.txt

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227212483-eac53a92-2e8e-47b8-97f2-e2a9616462d0.png)

**Comment by FuseFairy** [comment]
hmm....I think you still do not use check_version (), anyway, this is only a check, not necessary

**Comment by VIDRA4444** [comment]
I don't understand.

**Comment by FuseFairy** [comment]
![image](https://user-images.githubusercontent.com/78064680/227213172-1979cf47-0b31-43ec-8dd4-c4267fb0ce9c.png)
remove check_version() from here

**Comment by VIDRA4444** [comment]
😢

**Comment by FuseFairy** [comment]
modify DISCORD_BOT_TOKEN=your_token  toDISCORD_BOT_TOKEN="your_token"

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227214577-d5f0456d-fd36-4604-9b37-75db6f55e820.png)
like this?

**Comment by FuseFairy** [comment]
![image](https://user-images.githubusercontent.com/78064680/227215022-22f74b75-1a24-4354-9057-7e4ee8b69ae5.png)
no, modify .env

**Comment by VIDRA4444** [comment]
ah... It's already fixed.

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227215317-d275520c-c9e7-4754-8cec-acc25298d680.png)

**Comment by FuseFairy** [comment]
hmm... modify like this
```
if __name__ == '__main__':
    check_verion()
    bot.run("your discord token")
```

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227217660-77528dcf-b5f7-4d72-9055-b984c0727942.png)

**Comment by FuseFairy** [comment]
modify your bot.py:
```
import discord
import os
import src.log
import sys
import pkg_resources
from discord.ext import commands
from dotenv import load_dotenv

load_dotenv()

bot = commands.Bot(command_prefix='!', intents = discord.Intents.all())

# init loggger
logger = src.log.setup_logger(__name__)

@bot.event
async def on_ready():
    logger.info(f'{bot.user} is now running!')
    for Filename in os.listdir('./cogs'):
        if Filename.endswith('.py'):
            await bot.load_extension(f'cogs.{Filename[:-3]}')  
    print("Bot is Up and Ready!")
    try:
        synced = await bot.tree.sync()
        print(f"Synced {len(synced)} commands")
    except Exception as e:
        print(e)
        
@bot.command()
async def load(ctx, extension):
    await bot.load_extension(f'cogs.{extension}')
    await ctx.send(f'Loaded {extension} done.')

@bot.command()
async def unload(ctx, extension):
    await bot.unload_extension(f'cogs.{extension}')
    await ctx.send(f'Un-Loaded {extension} done.')

@bot.command()
async def reload(ctx, extension):
    await bot.reload_extension(f'cogs.{extension}')
    await ctx.send(f'Re-Loaded {extension} done.')

@bot.command()
async def clean(ctx):
    open('discord_bot.log', 'w').close()
    await ctx.send(f'Has been emptied')

if __name__ == '__main__':
    check_verion()
    bot.run("your token")
```

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227218621-e6fdcae2-1d93-40e9-a7cb-476c7329ca36.png)

**Comment by FuseFairy** [comment]
Update EdgeGPT==0.1.5, I see this package has just been updated

**Comment by VIDRA4444** [comment]
![image](https://user-images.githubusercontent.com/128645600/227222062-8b6ca37d-47a8-4f97-a617-2834f9228900.png)
but nothing...

**Comment by VIDRA4444** [comment]
Thanks a lot for trying to help man, but I'm already very tired, you and I have spent about 3 hours on this case, but all the errors new and new... Should I close the topic? I don't want to continue...
