### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VaRaMBaZ1** [FuseFairy/DiscordBot-EdgeGPT#24]
[2023-03-23 17:49:41] [INFO    ] discord.client: logging in using static token
[2023-03-23 17:49:43] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a0935931e1e2a1ed3a1d25fb82a08ca4).
[30;1m2023-03-23 17:49:45[0m [34;1mINFO    [0m [35m__main__[0m -> Bing#5232 is now running!
[2023-03-23 17:49:45] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 934, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\DiscordBot-EdgeGPT-main\cogs\edgegpt.py", line 7, in <module>
    from src.response import send_message
  File "D:\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\DiscordBot-EdgeGPT-main\src\response.py", line 7, in <module>
    from config.load_config import config
ModuleNotFoundError: No module named 'config.load_config'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "D:\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\DiscordBot-EdgeGPT-main\bot.py", line 38, in on_ready
    await bot.load_extension(f'cogs.{Filename[:-3]}')
  File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 937, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.edgegpt' raised an error: ModuleNotFoundError: No module named 'config.load_config'

**Comment by VIDRA4444** [comment]
ХАХАХАХАХ ебать ты падла

**Comment by VIDRA4444** [comment]
мне понравилось ю ар даун:)))) у них это вниз, а не оскорбление

**Comment by VaRaMBaZ1** [comment]
Хахаха, сижу тут уже часа 2 наверно, ошибку выдает, пиздец...

**Comment by VIDRA4444** [comment]
чувак, я тоже сижу тут уже несколько часов, ещё со вчера. сначала библиотека не работала, потом версия не та, потом версия другого не та блять а щас новая ошибка, я уж так заебался
Но это уже дело принципа. Я поставлю бота в свой ёбаный дискорд и буду им пользоваться! БЕСПЛАТНО

**Comment by VIDRA4444** [comment]
но самое забавное что часть ошибок мне помог решить тот же chatgpt, только третий

**Comment by FuseFairy** [comment]
I update repo, you can try again.

**Comment by FuseFairy** [comment]
> [2023-03-23 17:49:41] [INFO ] discord.client: logging in using static token [2023-03-23 17:49:43] [INFO ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a0935931e1e2a1ed3a1d25fb82a08ca4). �[30;1m2023-03-23 17:49:45�[0m �[34;1mINFO �[0m �[35m__main__�[0m -> Bing#5232 is now running! [2023-03-23 17:49:45] [ERROR ] discord.client: Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 934, in _load_from_module_spec spec.loader.exec_module(lib) # type: ignore File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "D:\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\DiscordBot-EdgeGPT-main\cogs\edgegpt.py", line 7, in from src.response import send_message File "D:\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\DiscordBot-EdgeGPT-main\src\response.py", line 7, in from config.load_config import config ModuleNotFoundError: No module named 'config.load_config'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 409, in _run_event await coro(*args, **kwargs) File "D:\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\DiscordBot-EdgeGPT-main\bot.py", line 38, in on_ready await bot.load_extension(f'cogs.{Filename[:-3]}') File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 1012, in load_extension await self._load_from_module_spec(spec, name) File "C:\Users\Dzhizus\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 937, in _load_from_module_spec raise errors.ExtensionFailed(key, e) from e discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.edgegpt' raised an error: ModuleNotFoundError: No module named 'config.load_config'

try to change response.py like this:
```
import discord
import asyncio
from discord.ext import commands
from EdgeGPT import Chatbot, ConversationStyle
from src import log
from config import load_config 

bot = commands.Bot(command_prefix='!', intents = discord.Intents.all())
logger = log.setup_logger(__name__)
sem = asyncio.Semaphore(1)

# to add suggest responses
class MyView(discord.ui.View):
    def __init__(self, chatbot: Chatbot, conversation_style:str):
        super().__init__()
        for label in suggest_responses:
            button = discord.ui.Button(label=label)
            # button event
            async def callback(interaction: discord.Interaction):
                await interaction.response.defer(ephemeral=False, thinking=True)
                # when click the button, all buttons will disable.
                for child in self.children:
                    child.disabled = True
                await interaction.followup.edit_message(message_id=interaction.message.id, view=self)
                username = str(interaction.user)
                usermessage = button.label
                channel = str(interaction.channel)
                logger.info(f"\x1b[31m{username}\x1b[0m : '{usermessage}' ({channel}) [Style: {conversation_style}] [button]")
                task = asyncio.create_task(send_message(chatbot, interaction, usermessage, conversation_style))
                await asyncio.gather(task)
                self.stop()
            self.add_item(button)
            self.children[-1].callback = callback
    
async def send_message(chatbot: Chatbot, message: discord.Interaction, user_message: str, conversation_style: str):
    async with sem:
        try:
            ask = f"> **{user_message}** - <@{str(message.user.id)}> (***style: {conversation_style}***)\n\n"
            if conversation_style == "creative":
                reply = await chatbot.ask(prompt=user_message, conversation_style=ConversationStyle.creative)
            elif conversation_style == "precise":
                reply = await chatbot.ask(prompt=user_message, conversation_style=ConversationStyle.precise)
            else:
                reply = await chatbot.ask(prompt=user_message, conversation_style=ConversationStyle.balanced)
            try:
                text = reply["item"]["messages"][1]["text"]
            except:
                text = reply["item"]["messages"][1]["adaptiveCards"][0]["body"][0]["text"]
            # maybe no url
            if len(reply['item']['messages'][1]['sourceAttributions']) != 0:
                i = 1
                all_url = ""
                for url in reply['item']['messages'][1]['sourceAttributions']:
                    text = str(text).replace(f"[^{i}^]", "")
                    all_url += f"{url['providerDisplayName']}\n-> [{url['seeMoreUrl']}]\n\n"
                    i+=1
                response = f"{ask}```{all_url}```\n{text}"
            else:
                response = f"{ask}{text}"
            # discord characters limit 
            while len(response) > 2000:
                temp = response[:2000]
                response = response[2000:]
                await message.followup.send(temp)
            if load_config.config["USE_SUGGEST_RESPONSES"]:
                global suggest_responses
                suggest_responses = []
                try:
                    # add all suggest in list
                    for suggest in reply["item"]["messages"][1]["suggestedResponses"]:
                        suggest_responses.append(suggest["text"])
                    await message.followup.send(response, view=MyView(chatbot, conversation_style))
                except:
                    await message.followup.send(response)
            else:
                await message.followup.send(response)
        except Exception as e:
            if reply["item"]["result"]["value"] == "Throttled":
                await message.followup.send("> **Error: We're sorry, but you've reached the maximum number of messages you can send to Bing in a 24-hour period. Check back later!**")
                logger.exception(f"Error while sending message: {reply['item']['result']['error']}")
            else:
                await message.followup.send("> **Error: Something went wrong, please try again later or reset Bing!**")
                logger.exception(f"Error while sending message: {e}")
```
