### ISSUE TITLE
Wrong button

### ISSUE THREAD

**Issue by hello-navi** [FuseFairy/DiscordBot-EdgeGPT#32]
When I press the first or second suggested response button, it always thinks I pressed the third button instead.

**Comment by FuseFairy** [comment]
Can you provide more information? Because I didn't find anything unusual when I tested it myself.

**Comment by FuseFairy** [comment]
How do you confirm that Bing's response is always the third button? Is it because the response doesn't match the question?

**Comment by FuseFairy** [comment]
The problem has been solved.
