### ISSUE TITLE
[Feature Request] Clickable source links

### ISSUE THREAD

**Issue by hello-navi** [FuseFairy/DiscordBot-EdgeGPT#35]
The source links look pretty ugly and take up a lot of space, with both the titles and the bare URLs in the code block. Is it possible to make them clickable links that just show the title and source number? Using embeds.

**Comment by FuseFairy** [comment]
Sounds great, I will try it

**Comment by FuseFairy** [comment]
but embeds  are no support url  for an embed field, I need to find another way

**Comment by hello-navi** [comment]
I meant something like this, the blue part is clickable link. I think that's an embed but I might be wrong.
![image423](https://user-images.githubusercontent.com/126853352/227699552-88247bc9-9ca6-4543-9b86-032e5b12d65c.png)

**Comment by hello-navi** [comment]
I think this is how you add links in embeds:  \[title](https://url)

**Comment by FuseFairy** [comment]
great work, thank you so much
