### ISSUE TITLE
"/create_image" doesn't work

### ISSUE THREAD

**Issue by occultwave** [FuseFairy/DiscordBot-EdgeGPT#48]
` [BingImageCreator]
ERROR: <bound method ClientResponse.text of <ClientResponse(https://www.bing.com/images/create?q=a%20cat%20drawind%20a%20landscape%20of%20green%20mountains&rt=3&FORM=GENCRE) [200 OK]>
<CIMultiDictProxy('Content-Length': '41111', 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Content-Encoding': 'gzip', 'Expires': '-1', 'Pragma': 'no-cache', 'Vary': 'Accept-Encoding', 'UserAgentReductionOptOut': 'A7kgTC5xdZ2WIVGZEfb1hUoNuvjzOZX3VIV/BA6C18kQOOF50Q0D3oWoAm49k3BQImkujKILc7JmPysWk3CSjwUAAACMeyJvcmlnaW4iOiJodHRwczovL3d3dy5iaW5nLmNvbTo0NDMiLCJmZWF0dXJlIjoiU2VuZEZ1bGxVc2VyQWdlbnRBZnRlclJlZHVjdGlvbiIsImV4cGlyeSI6MTY4NDg4NjM5OSwiaXNTdWJkb21haW4iOnRydWUsImlzVGhpcmRQYXJ0eSI6dHJ1ZX0=', 'Content-Security-Policy-Report-Only': "script-src https: 'strict-dynamic' 'report-sample' 'nonce-L6U+wCzYpxT+nQmbcSXHCgeIawuWHTOUkATQhqWKMXU='; base-uri 'self';report-to csp-endpoint", 'Report-To': '{"group":"csp-endpoint","max_age":86400,"endpoints":[{"url":"https://aefd.nelreports.net/api/report?cat=bingcsp"}]}', 'P3P': 'CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"', 'Date': 'Sat, 08 Apr 2023 21:54:18 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'GI_FRE_COOKIE=gi_prompt=2; domain=.bing.com; path=/; secure; SameSite=None', 'Alt-Svc': 'h3=":443"; ma=93600', 'X-CDN-TraceID': '0.76b91302.1680990858.5c91ab86')>
>
←[30;1m2023-04-09 00:54:19←[0m ←[31mERROR   ←[0m ←[35msrc.imageCreate←[0m -> Error while create image: Redirect failed
←[31mTraceback (most recent call last):
  File "C:\Users\user\Bot\DiscordBot-EdgeGPT-main\src\imageCreate.py", line 25, in create_image
    images = await image_generator.get_images(prompt)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\BingImageCreator.py", line 237, in get_images
    raise Exception("Redirect failed")
Exception: Redirect failed←[0m`

**Comment by FuseFairy** [comment]
https://github.com/acheong08/BingImageCreator/issues/7
Maybe using inappropriate prompt, so you get the error.

**Comment by occultwave** [comment]
> [acheong08/BingImageCreator#7](https://github.com/acheong08/BingImageCreator/issues/7) Maybe using inappropriate prompt, so you get the error.

I tried to enter prompt from the guide, it also doesn't work

**Comment by FuseFairy** [comment]
https://github.com/acheong08/BingImageCreator/issues/2
well,there is no clear solution for this error at the moment, sorry.

**Comment by occultwave** [comment]
I found a solution to the problem. I just went back to bing and copied fresh cookies from there, everything worked.
