### ISSUE TITLE
[Feature Request] user = own chat

### ISSUE THREAD

**Issue by InfiniteCod3** [FuseFairy/DiscordBot-EdgeGPT#55]
I wish there was a setting that would create a separate chat for each user, so that the conversations would not get mixed up in one chat. For instance, if I asked what if Corvette C8 was an SUV and then asked what question I asked, it should reply that I asked if Corvette C8 was an SUV. But if another Discord user asked about the question that was asked, it should start a new chat with them, while remembering the old chat with me.

**Comment by FuseFairy** [comment]
Latest version can create a separate chat for each user. If there is a problem, return it to me, thank you~
