### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Murat1Ahmet** [FuseFairy/DiscordBot-EdgeGPT#66]
The bot so nice and there is 2 features will make it even better

*Targeting channel like let server owner setup channel for replyall messsages.
*Make suggest text for the create_image too like the website when you create image there is suggest like add hat, glasses etc...

**Comment by FuseFairy** [comment]
I plan to use mention and thread to reply all messsages.

Make suggest text  like this?
![image](https://user-images.githubusercontent.com/78064680/236362073-d7467a03-283a-4147-b4c7-07a657f8c7ab.png)

**Comment by Murat1Ahmet** [comment]
Yes Exactly

**Comment by FuseFairy** [comment]
create_image can't make suggest  text.only /bing can do this.

**Comment by Murat1Ahmet** [comment]
alright thx for the try, just replyall wtih (mention and thread) still nice

**Comment by FuseFairy** [comment]
thread to look later, I don't have enough time, haha
