### ISSUE TITLE
New Future

### ISSUE THREAD

**Issue by Murat1Ahmet** [FuseFairy/DiscordBot-EdgeGPT#74]
As there is daily limitation in bing, Is it possible to make future like users add there cookies to use the bot, like that will let everyone use the bot, now 1 user can finish daily of bing

**Comment by Murat1Ahmet** [comment]
> you can use this command to update cookies. ![image](https://user-images.githubusercontent.com/78064680/239013710-d159896e-27aa-4a3d-b92d-59c02c6e622c.png) However, if you want everyone to use this command, just delete line 88 code `@commands.is_owner()` in bot.py file.

yes but there is maximium daily limit

**Comment by FuseFairy** [comment]
So you want everyone to be able to use their own cookies?

**Comment by Murat1Ahmet** [comment]
> So you want everyone to be able to use their own cookies?

yes:)
