### ISSUE TITLE
Image Generation (Error: Redirect failed)

### ISSUE THREAD

**Issue by GmeX1** [FuseFairy/DiscordBot-EdgeGPT#75]
Hello, i've just installed a bot, it's running locally on my machine.
On every image generation attempt bot sends me "Error: Redirect failed" message (tried both /create_image and /bing). I've tried to update cookies, but that didn't solve the issue.
Tell me if you need logs, I'll send them here.

**Comment by FuseFairy** [comment]
Strange error, I've encountered it before, but it gets better in a few days. You can borrow cookies from someone else and try again.

**Comment by GmeX1** [comment]
Okay, I'll try that, thank you.
