### ISSUE TITLE
Privileged Gateway Intents

### ISSUE THREAD

**Issue by TommyNoble1** [FuseFairy/DiscordBot-EdgeGPT#77]
Hello, can you explain why the bot needs these 2 gateways intents pls, I don't see any future in the bot needs them both, just message content the bot needs it yes. 
Server Members Intent, Presence Intent, when i turn any of them off the bot doesn't work, so can you tell me which commands that use these 2 pls

Server Members Intent
This intent allows your bot to see the list of members in a Discord server. This is necessary for many bot features, such as moderation, role management, and user management.
,
Presence Intent
This intent allows your bot to see the online status of users in Discord servers. This is necessary for many bot features, such as chat bots, notifications, and game integrations.

**Comment by FuseFairy** [comment]
you're right, we don't need Server Members Intent and Presence Intent, I just tend to open it all by the way. If you want turn off  them, modify line12 in bot.py file.
```
bot = commands.Bot(command_prefix='!', intents=discord.Intents.default())
```

**Comment by TommyNoble1** [comment]
I changed it for,  bot = commands.Bot(command_prefix='!', intents = discord.Intents(messages=True)) 
and i still getting error

**Comment by FuseFairy** [comment]
but I'm still work, hmm...
