### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by Murat1Ahmet** [FuseFairy/DiscordBot-EdgeGPT#80]
how to fix and avoid this error pls 
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.

**Comment by FuseFairy** [comment]
where is your bot host?

**Comment by Murat1Ahmet** [comment]
> where is your bot host?

techstar host

**Comment by Murat1Ahmet** [comment]
I've changed in bot.py to that as i saw in pervoius issue, is that why i get api limit ?
how can i fix it
bot = commands.Bot(command_prefix='!', intents = discord.Intents(messages=False))

**Comment by FuseFairy** [comment]
There is no relationship between the two

**Comment by Murat1Ahmet** [comment]
> There is no relationship between the two, your API limit is because of too many requests.

oh so the bot doesn't support muti user support?

**Comment by FuseFairy** [comment]
support, but too many requests will got  error.

**Comment by Murat1Ahmet** [comment]
> support, but too many requests will got error. Try run bot local, will it get API limit?

it work yaa, then its host issue ? or like discord has api limit just in providers hosts i still didnt get it sorry

**Comment by FuseFairy** [comment]
ya, I'm think is ip issue

**Comment by Murat1Ahmet** [comment]
okay thanks
