### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Murat1Ahmet** [FuseFairy/DiscordBot-EdgeGPT#81]
I dont know if its easy or hard tbh, i'll just suggest it and up to you

Make option to user to choose setting his own cookies as user set or server set (maybe just owner or everyone up to you)
Like user set, will let *user* talk from the cookies he set 
Server set, will let *everyone in server* talk from the cookies he set

**Comment by FuseFairy** [comment]
I think the mention is enough for the time being,  will have a chance to look at it later
