### ISSUE TITLE
Clickable URLS

### ISSUE THREAD

**Issue by AndrewsPanda** [FuseFairy/DiscordBot-EdgeGPT#86]
Thank you for fixing the broken URL links displayed in Discord chat. It works and functions a lot better now.

Is it possible for the URLS Bing provides in it's answers to carry through to discord as clickable links or will that break it?

For example:

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/1265156/e5260a58-ec10-4299-9118-6ece5441b261)

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/1265156/63a335e9-7bc1-441a-83ea-0dcc10efd0c1)

Thanks again! You're amazing

**Comment by FuseFairy** [comment]
not sure, I will try it.

**Comment by FuseFairy** [comment]
It's impossible.
