### ISSUE TITLE
BardGPT

### ISSUE THREAD

**Issue by AndrewsPanda** [FuseFairy/DiscordBot-EdgeGPT#87]
EdgeGPT is fantastic! I was hoping you could make a BardGPT version of your bot. 

ie; https://github.com/armintum/Bard-Discord-bot 

It currently connects through __Secure-1PSID

The functions of your EdgeGPT bot being able to upload cookies per user and how it functions is amazing. It would be good to have the same for Bard. Bard tends to display tables a lot. One thing I've noticed when using any GPT AI through discord is the tables don't carry through. I'm not sure if its possible for them to carry through to Discord properly.

Anyway, I digress. Happy to sponsor.

**Comment by FuseFairy** [comment]
Ok, I will do it later.
