### ISSUE TITLE
One cookie file for everyone

### ISSUE THREAD

**Issue by HeroWarriors** [FuseFairy/DiscordBot-EdgeGPT#90]
Please make it so that not every user has to upload a cookies file.

**Comment by FuseFairy** [comment]
can mention bot, mention is for everyone.

**Comment by FuseFairy** [comment]
only generate  by conversation

**Comment by HeroWarriors** [comment]
So if I say to generate will it generate one and send it? If I use mention.

**Comment by FuseFairy** [comment]
yes, but you need switch conversation to Creative first.

**Comment by FuseFairy** [comment]
I think I can let /create_image command have personal and public two types.
