### ISSUE TITLE
Same cookies file after restart

### ISSUE THREAD

**Issue by ghost** [FuseFairy/DiscordBot-EdgeGPT#91]
Is there a way to prevent uploading the same cookies.json file after restart? I would restart the bot quite often, but that means that every time I restart the bot, everybody who want's to use slash command has to upload the cookies.json file again.

**Comment by FuseFairy** [comment]
Haven't thought of a good way yet.
Why do you need to restart the bot quite often?

**Comment by coyottetv** [comment]
for me too I have to restart it once a day and there is no possibility of deleting the functionality or do people not need to add their cookies?

**Comment by coyottetv** [comment]
just one question is that there is a possibility that the bot retrieves the cookies automatically without having to restart the bot I explain I mean when the cookies are expected that the bot manages to retrieve a new session by itself with cookies up to date I don't know if this is possible or if it's a too complicated idea to add :)

**Comment by FuseFairy** [comment]
if you mean is auto update cookies, I'm tried, but it failed.

**Comment by coyottetv** [comment]
oh ok no worries

**Comment by FuseFairy** [comment]
I can use SQLite to storage of individual cookies, so it doesn't reset when the bot restarts. Like my other [repo](https://github.com/FuseFairy/DiscordBot-BardGPT) .
