### ISSUE TITLE
Error: Redirect failed

### ISSUE THREAD

**Issue by Coderboi4** [FuseFairy/DiscordBot-EdgeGPT#93]
It happened when i ran /create-image! pleaes fix asap

**Comment by FuseFairy** [comment]
try to upgrade EdgeGPT==0.8.1

**Comment by Coderboi4** [comment]
> try to upgrade EdgeGPT==0.8.1

Still..

**Comment by FuseFairy** [comment]
use ```pip install BingImageCreator==0.4.1```, the api author fixed this problem in ver0.4.1, just in case, you should also update the cookies.

**Comment by Coderboi4** [comment]
> use `pip install BingImageCreator==0.4.1`, the api author fixed this problem in ver0.4.1, just in case, you should also update the cookies.


done and still same error :(

**Comment by AndrewsPanda** [comment]
I have tested the previous version and the updated version both locally and deployed. Both are working fine.

**Comment by FuseFairy** [comment]
> > use `pip install BingImageCreator==0.4.1`, the api author fixed this problem in ver0.4.1, just in case, you should also update the cookies.
> 
> 
> done and still same error :(

The only possibility is that there is a problem with your cookies or the ip location.
