### ISSUE TITLE
Error: InvalidRequest: Culture is not supported. (Parameter 'name') English-United Kingdom is an invalid culture identifier.

### ISSUE THREAD

**Issue by DamianWing** [FuseFairy/DiscordBot-EdgeGPT#94]
getting this when requesting anything from bing chat, and then request failed when generating an image

**Comment by FuseFairy** [comment]
I'm update bing api, try again

**Comment by de-joit** [comment]
Sorry for the late reply. It seems everything is now working properly, no errors. Thank you!
