### ISSUE TITLE
Problem starting the bot

### ISSUE THREAD

**Issue by Jnss98b** [FuseFairy/DiscordBot-EdgeGPT#96]
So I ran `pip install -r requirements.txt`, renamed `.env.dev` to `.env` and filled out `DISCORD_BOT_TOKEN`, and pasted my cookies into `cookies.json` but somehow it's still complaining that EdgeGPT module is missing?
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/24306400/76df02e6-e0d6-4dcc-a9df-a0fa4095cbde)

I can even see it under ib site-packages and I set the PATH variable to point to site-packages already too
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/24306400/2f878615-3f4f-4c9a-9dd2-b456cd6b7db1)

**Comment by FuseFairy** [comment]
Check if the edgegpt version is 0.11.2

**Comment by Jnss98b** [comment]
It is indeed 0.11.2
![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/24306400/655f01f3-e475-47f4-a9af-fc26304ea683)

**Comment by FuseFairy** [comment]
what's your python version

**Comment by Jnss98b** [comment]
3.11.4

**Comment by FuseFairy** [comment]
Maybe is python version problem, I'm using 3.9.16

**Comment by Jnss98b** [comment]
Oh was this fixed? What was the problem?

**Comment by FuseFairy** [comment]
no, I'm can work in python version 3.11.4,  try running this simple code if you can

```
import asyncio, json
from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle

async def main():
    bot = await Chatbot.create() # Passing cookies is "optional", as explained above
    response = await bot.ask(prompt="Hello world", conversation_style=ConversationStyle.creative, simplify_response=True)
    print(json.dumps(response, indent=2))

    await bot.close()

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by Jnss98b** [comment]
Run this in the python interpreter?

**Comment by FuseFairy** [comment]
yes

**Comment by Jnss98b** [comment]
This is what I got after running the snippet above

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/24306400/1c80608e-5c7e-453f-9e82-a1fb723d2944)

**Comment by FuseFairy** [comment]
oh, you have to modify the location where you put cookies

**Comment by Jnss98b** [comment]
In what file is the cookies path stored?

**Comment by Jnss98b** [comment]
Oh wait I got what you meant

**Comment by Jnss98b** [comment]
Similar error

![image](https://github.com/FuseFairy/DiscordBot-EdgeGPT/assets/24306400/4b1b076b-707c-4d9d-950b-c41cd7c5cfe2)

**Comment by FuseFairy** [comment]
API has error, waiting for fixes

**Comment by FuseFairy** [comment]
My chatbot can working now, but I still can't reproduce this error.

**Comment by Jnss98b** [comment]
Will try to start from the beginning with a new copy of the repo and report back
